// Vietnamese translations for Key Numbers
const destiny_map = new Map<number, string>([
    [1, "Sứ mệnh của bạn trong cuộc đời này là trau dồi bản thân và trở thành một người lãnh đạo. Mục đích cuộc đời bạn là kiên cường, độc lập, tiên phong, phát kiến và đưa vai gánh vác mọi việc – tất cả là để phát triển ý thức về bản ngã, ý chí và sự quyết tâm của bạn. Học cách tự lập, suy nghĩ cho chính mình và khiến mình trở nên cá tính cũng như những điều mới, những tư tưởng mới và các hoạt động sáng tạo mang đến những cơ hội lớn để bạn vươn tới sứ mệnh của mình. Bạn sinh ra là để lãnh đạo. Hãy là một người lãnh đạo và dạy cách trở thành một người lãnh đạo."],
    [2, "Sứ mệnh của bạn trong cuộc đời này là tạo ra sự hài hòa. Mục tiêu của bạn là tìm kiếm sự hợp tác, cân bằng và là một đối tác kiên nhẫn – tất cả là để phát triển ý thức của bạn về mối quan hệ. Bạn cần học về lòng trắc ẩn và tiếp nhận mọi thứ bằng cảm xúc. Khả năng thích nghi và tạo sức thuyết phục sẽ đưa bạn đến gần sứ mệnh của mình hơn. Bạn sinh ra là để xây dựng hòa bình. Hãy tiến lên và chia sẻ về nó."],
    [3, "Mục đích của bạn trong cuộc đời này là tiếp thêm sinh lực và sức mạnh. Mục đích của bạn là khuyến khích người khác thông qua những hi vọng và niềm tin của bạn, sử dụng sự sáng tạo đầy cảm hứng của bạn để giúp người khác cùng trải nghiệm niềm vui. Học cách thể hiện cảm xúc của bạn thông qua tài năng sử dụng từ ngữ và sự sôi nổi, nhiệt huyết và thông minh sẽ giúp bạn tiến tới sứ mệnh của mình. Bạn sinh ra là để thể hiện bản thân, hãy trò chuyện, luôn tích cực và khuyến khích mọi người."],
    [4, "Sứ mệnh của bạn trong cuộc đời này là xây dựng một cái gì đó có giá trị lâu dài. Mục tiêu của bạn là trở nên thực tế, làm việc chăm chỉ đồng thời giữ mọi thứ trật tự, ngăn nắp để đảm bảo nhu cầu được an toàn. Học cách thể hiện những giá trị truyền thống và sự trung thành, kiên định sẽ giúp bạn hoàn thành sứ mệnh của mình. Bạn sinh ra là để quản lý và thiết lập trật tự. Hãy tạo dựng nền tảng và phát triển mọi thứ từ đó."],
    [5, "Sứ mệnh của bạn trong cuộc đời này là điều chỉnh, phát triển và tiến bộ. Mục đích của bạn là nắm lấy các cơ hội và quyền tự chủ, và theo đuổi trí tò mò vô tận của mình, đồng thời vận dụng sự tháo vát cũng như sự cuốn hút để luôn tiến về phía trước. Học cách thể hiện sự khéo léo và trở thành một linh hồn tự do sẽ giúp bạn tiến tới sứ mệnh của mình. Bạn được sinh ra là để được giải phóng và tự do. Hãy tiến về phía trước và thích nghi uyển chuyển với mọi sự thay đổi."],
    [6, "Sứ mệnh của bạn trong cuộc đời này là phục vụ. Mục tiêu của bạn là chăm sóc gia đình và những người thương yêu đồng thời sử dụng sự ngưỡng mộ và yêu mến của bạn đối với mọi người và những điều tinh tế để thiết lập sự gần gũi, thân thiết xung quanh bạn. Học cách để bày tỏ lòng vị tha cũng như mang lại cho người khác sự thoải mái, dễ chịu sẽ giúp bạn tiến tới mục tiêu của mình. Bạn sinh ra là để nuôi dưỡng và làm đẹp. Hãy yêu thương bằng sự cân bằng và bình ổn."],
    [7, "Sứ mệnh của bạn trong cuộc đời này là tìm tòi và nghiên cứu. Mục đích của bạn là đào sâu vấn đề và chiêm nghiệm tất cả những gì xảy ra trong cuộc đời này. Sử dụng khả năng phân tích và sự tỉ mỉ của mình để tìm kiếm trí huệ. Học cách thể hiện sự kỹ lưỡng sắc sảo của mình cũng như sự chu đáo và sáng suốt sẽ đưa bạn tới gần mục tiêu của mình. Bạn sinh ra là để khai mở thế giới. Hãy tập trung và rèn giũa sự thông thái của bạn."],
    [8, "Sứ mệnh của bạn trong cuộc đời này là có được sự tự kiểm soát bản thân. Mục đích của bạn là tự hoàn thiện, sử dụng khả năng của bạn trong kinh doanh và tổ chức. Học cách để thể hiện bản chất đích thực, khám phá sức mạnh của chính mình và tầm nhìn khoáng đạt sẽ đưa bạn tiến gần đến sứ mệnh của mình. Bạn sinh ra là để có được sự thành công và giàu có vật chất. Hãy nhận thức được điều này và trở thành một nhà lãnh đạo kiệt xuất."],
    [9, "Sứ mệnh của cuộc đời bạn là vươn tới sự hoàn mỹ và yêu thương vô điều kiện. Mục tiêu của bạn là vươn tới những linh hồn tiến hóa cao hơn trong vũ trụ này bằng sự nhân đạo, lòng thương cảm và nghệ thuật chữa lành của mình. Học cách chuyển hóa, chữa lành, sẵn sàng tiếp thu, lĩnh hội những ý tưởng mới và một tấm lòng khoan dung độ lượng sẽ đưa bạn lại gần sứ mệnh của mình. Bạn sinh ra là để vươn tới những chân trời mới. Hãy vươn tay ra để giúp đỡ mọi người."],
    [10, "Sứ mệnh của bạn trong cuộc đời này là trau dồi bản thân và trở thành một người lãnh đạo. Mục đích cuộc đời bạn là kiên cường, độc lập, tiên phong, phát kiến và đưa vai gánh vác mọi việc – tất cả là để phát triển ý thức về bản ngã, ý chí và sự quyết tâm của bạn. Học cách tự lập, suy nghĩ cho chính mình và khiến mình trở nên cá tính cũng như những điều mới, những tư tưởng mới và các hoạt động sáng tạo mang đến những cơ hội lớn để bạn vươn tới sứ mệnh của mình. Bạn sinh ra là để lãnh đạo. Hãy là một người lãnh đạo và dạy cách trở thành một người lãnh đạo."],
    [11, "Sứ mệnh của bạn trong cuộc đời này là truyền cảm hứng và chiếu sáng. Mục đích của bạn – như một linh hồn già dặn – đó là sống xứng đáng và chấp nhận sứ mệnh của mình, và nhận ra rằng sự sáng tạo cùng với khả năng nhận thức thấu đáo sẽ mang đến những điều tốt lành cho nhân loại. Phận sự của bạn là phục hồi, tăng trưởng và chuyển hóa cuộc sống của những người khác. Học cách thể hiện khả năng khai sáng của mình, vững vàng trước thách thức và tạo sức ảnh hưởng lên nhiều người khác sẽ mang đến cơ hội để bạn nắm lấy vận mệnh của mình. Bạn được sinh ra là để trở thành người lãnh đạo truyền cảm hứng. Hãy sống có đạo đức và bạn sẽ trở thành người lãnh đạo – vị trí vốn dành cho bạn."],
    [22, "Sứ mệnh của bạn trong cuộc đời này là biến những giấc mơ trở thành sự thật và thực hiện những kế hoạch, những dự án mang lại lợi ích cho nhân loại. Mục đích của bạn là để mọi thứ diễn ra bằng cách dùng những nguyên lý tinh thần để làm việc một cách thực tế trong thế giới vật chất. Học cách thể hiện năng lực, sự tinh thông lão luyện của mình, thực tế và trung thành với bản chất tự nhiên của mình đó là không bao giờ lùi bước, bạn sẽ hoàn thành sứ mệnh của mình. Bạn được sinh ra là để trở thành BậcThầy Xây Dựng. Hãy mang những quy luật tinh thần để áp dụng vào thế giới vật chất."],
])
const overview_map = new Map<number, string>([
    [1, "Số 10 (hoặc 1), Tượng trưng cho sự mạnh mẽ, thủ lĩnh, chỉ huy, lãnh đạo, tự chủ. Bạn cố gắng hết sức, phấn đấu đạt đến điều tốt nhất. Chưa có con số nào lại có một khả năng dao động lớn và rộng như vậy đối với những con người Số 10. Khi sống tích cực, họ có thể là một người rất quảng giao, được yêu thích trong xã hội, nhưng khi sống tiêu cực, họ có thể là những cá nhân hết sức chao dao, lạc lối, bất an. Họ là những người dễ thích nghi nhất trong tất cả các số. Họ có tiềm năng để nắm bắt những thành công rực rỡ, nhưng họ cũng có thể mòn mỏi trong sự tầm thường."],
    [2, "Số 2 nhìn chung là người nhạy cảm, ít võ đoán, đầy thiện chí giúp đỡ người khác, trong khi số 22/4 lại rất quyết đoán và tự tin."],
    [3, "Số 3 nằm ở vị trí đầu bảng của trục ngang Trí não, chúng ta hiểu vì sao những người Số 3 nhấn rất mạnh ở phần tư duy và lý luận."],
    [4, "Trong thế giới hiện đại, rất nhiều các vấn đề được nhiều người quan tâm có liên quan đến các khía cạnh vật chất. Vì vậy, các biểu hiện cơ bản của người Số 4 nằm ở khía cạnh này sẽ dễ dàng được thỏa mãn. Tuy vậy, người Số 4 vẫn còn nhiều điều nữa để quan tâm hơn là chỉ khía cạnh vật chất, dù phần lớn sự quan tâm của họ nằm ở mặt này, bởi số 4 nằm ở trung tâm trục ngang Thể chất 1-4-7."],
    [5, "Trên thực tế, người có Con số chủ đạo là 5 thường có khuynh hướng cố gắng thoát khỏi những sự trói buộc. Đây là một biểu hiện tự nhiên của bản chất nhạy cảm cao của họ, và một nhu cầu thường trực cần bày tỏ các cảm xúc của mình. Cũng không ngạc nhiên khi nhìn vào biểu đồ số theo trường phái Pythagoras, Số 5 nằm ở giữa trục ngang Tâm hồn và giữa luôn Mũi tên chỉ Ý chí."],
    [6, "Đây là con số chủ đạo của những sự tột bực, hoặc 'quá mức' (extremes). Những người Số 6, khi chọn hướng về lối sống tích cực, họ có khả năng sáng tạo to lớn, tuy vậy họ cũng dễ trở thành những người lo lắng thường trực khi sống tiêu cực. Vị trí của số này nằm ngay giữa trục ngang Trí não và ở đầu Mũi tên Ý Chí (sau loạt bài về Con số chủ đạo, mình sẽ chia sẻ tiếp phần Các Mũi tên cá tính), điều này làm cho người Số 6 có một tiềm năng khổng lồ trong việc tiếp nhận và sáng tạo một cách sáng chói. Đáng tiếc là họ thường hiếm khi đạt được thành công lâu dài trong cuộc sống do hay bị chia trí vào việc băn khoăn, lo lắng, làm cho họ tự mất năng lượng."],
    [7, "Dưới ảnh hưởng của Số 7 trong vai trò Con số chủ đạo, người mang số này sẽ triệt để trải nghiệm các bài học đời, cả thông qua những thử thách hy sinh hoặc thông qua tiến trình dạy người hoặc chia sẻ với người. Cả hai phương diện học hỏi này đều thể hiện ở khía cạnh trải nghiệm thể chất, do số 7 nằm ở điểm giao nhau giữa hai Mũi tên: Mũi tên Thực tế và Mũi tên Hoạt động."],
    [8, "Những người mang Con số chủ đạo 8 là những người coi tính độc lập tự chủ là một trong những yếu tố quan trọng hàng đầu trong cuộc sống. Họ có thể là những người tích hợp nhiều yếu tố khác biệt, sở hữu cá tính mạnh, sức mạnh và trí tuệ hơn người. Quyền năng của họ được rút ra từ vị trí số 8 là con số của trí tuệ ở Trục ngang Tâm hồn, cũng như số 8 nằm ở trung tâm Mũi tên Hoạt động."],
    [9, "Những người mang Con số chủ đạo 9 sẽ nhân gấp ba lần ba yếu tố: ước vọng/hoài bão, trách nhiệm, và lý tưởng sống so với một người bình thường. Những người này, luôn đặt yếu tố con người lên hàng đầu."],
    [10, "Số 10 (hoặc 1) Tượng trưng cho sự mạnh mẽ, thủ lĩnh, chỉ huy, lãnh đạo, tự chủ. Bạn cố gắng hết sức, phấn đấu đạt đến điều tốt nhất. Chưa có con số nào lại có một khả năng dao động lớn và rộng như vậy đối với những con người Số 10. Khi sống tích cực, họ có thể là một người rất quảng giao, được yêu thích trong xã hội, nhưng khi sống tiêu cực, họ có thể là những cá nhân hết sức chao dao, lạc lối, bất an. Họ là những người dễ thích nghi nhất trong tất cả các số. Họ có tiềm năng để nắm bắt những thành công rực rỡ, nhưng họ cũng có thể mòn mỏi trong sự tầm thường."],
    [11, "Con số chủ đạo 11 có một mức độ tâm linh đặc biệt cao bao quanh, làm cho những ai sinh ra dưới Con số chủ đạo này dễ có một tiềm năng phát triển Tầng Ý thức Cao rất mạnh. Tuy vậy, phần lớn những người số này lại không đủ khả năng phát triển những tiềm năng tiềm ẩn này, nhưng hy vọng điều này sẽ sớm bị phá vỡ cùng với sự phát triển của thời đại mới – thời đại phát triển nhận thức (thế kỷ 21). Mặc dù Số 11 cũng không phổ biến như nhiều Con số chủ đạo khác, nhưng họ chắc chắn sẽ có cơ hội đẩy mạnh tiềm năng mà họ đang có, một khi họ ý thức được bản thân họ có giá trị tinh thần cao đến thế nào."],
    [22, "Đây là một con số đặc biệt, là ‘Con số vua’ – Master number. Những người sinh ra có Con số chủ đạo là 22/4 có tiềm năng hầu như vô giới hạn và thường đạt được hầu hết những mục đích dường như bất khả thi. Nhưng thực tế có hai kiểu người Số 22/4 hoàn toàn khác biệt: kiểu người nhận thức được sức mạnh của họ và kiểu người không nhận thức được. Sự khác biệt giữa hai kiểu người này cũng tột bực như bản thân sức mạnh của con số này vậy. Kiểu người Số 22/4 biết nhận thức được sức mạnh của mình lĩnh hội được sự thành công của hầu như mọi mặt trong cuộc sống mà họ được hướng dẫn tới, kiểu người 22/4 không nhận thức được lại chìm vào cách sống ơ hờ đầy lười biếng, trở thành những người hầu như vô dụng, lạc lõng giữa đời, không ít người trong số này thậm chí còn bị chìm nổi trong các viện tâm thần. Cách mô tả của tác giả làm mình liên tưởng tới một khái niệm khá cực đoan hiện hữu: 'Được ăn cả - Ngã về không'. Chỉ có một trường hợp số tổng cộng ngày sinh cho ra con số đặc biệt này, đó là 22, và như vậy, người ta sẽ đặt cho nó một dạng ký hiệu đặc biệt: 22/4, đặc biệt hiếm, chỉ chiếm khoảng 1-2% toàn tổng số dân trong một đất nước. "],
])
const purposeOfLife_map = new Map<number, string>([
    [1, ""],
    [2, "Những người Số 2 có một khả năng đặc biệt để làm việc dưới trướng một người lãnh đạo năng động. Nếu không gặp được lãnh đạo như thế, họ dễ dàng cảm thấy lạc lối. Thường thì bản thân họ khó trở thành lãnh đạo, cũng hiếm khi có tham vọng lên làm lãnh đạo, nhưng họ có một khả năng độc đáo để tìm kiếm và hợp tác với những người hay những tổ chức có thể đánh giá cao nhất khả năng cần cù, tận tụy của họ. Vai trò đặc biệt của họ là để hoàn thiện vấn đề bằng chính sự trung thành, tận tụy bằng trực giác của họ."],
    [3, "Những người Số 3 sẽ có những mục đích chính liên quan tới các khả năng tư duy, suy nghĩ. Họ đặt tầm quan trọng lên mục tiêu thấu hiểu cuộc sống cùng với sự phát triển cá tính, có điều những điều này có liên quan đến khả năng vận dung tư duy của họ nhiều hơn là các trải nghiệm thực tế hay vận dụng trực giác. Những điều họ phụng sự cuộc sống được diễn đạt thông qua việc tư duy, lên kế hoạch, phân tích, ghi nhớ, v.v…"],
    [4, "Bởi chúng ta sống trên cõi đời này trong một cơ thể vật chất, vì vậy cũng chẳng có gì ngạc nhiên khi rất nhiều trải nghiệm của chúng ta có liên quan đến khía cạnh vật chất của đời sống. Người Số 4 đặc biệt chú trọng những trải nghiệm và biểu hiện về thể chất, là yếu tố then chốt cho sự phát triển giai đoạn đầu của họ. Nhưng sau này khi trưởng thành, họ sẽ có khuynh hướng tự nhiên nắm bắt thêm được khả năng tổ chức của trục Thể chất, từ đó tạo điều kiện cho họ phát triển rộng thêm về tình yêu thương, ý thức và trí tuệ."],
    [5, "Diễn đạt cảm xúc một cách toàn vẹn nhất (thông qua các hình thức như viết, vẽ, điêu khắc, vv…) là một trong những điều tinh tế mà con người mơ đạt tới. Tuy nhiên, điều này chỉ có thể đạt được khi con người ta đủ tự do để thể hiện. Đó chính là cái mà những người Số 5 tìm kiếm để phát triển, như một cách để thấu hiểu các tầng cảm xúc của họ. Tuy vậy, rất ít người Số 5 nhận ra điều này, họ chỉ cảm nhận được là họ đang cảm thấy thôi thúc được tự do mà thôi, mà không hề nhìn ra nguyên nhân thực sự ẩn đàng sau đó. Đó cũng chính là điều cần học hỏi, để định hướng một cách tích cực cuộc đời của họ bằng những phương tiện biểu hiện này."],
    [6, "Chúng ta nhìn thấy rất nhiều người Số 6 giỏi giang trong rất nhiều lĩnh vực sáng tạo, từ ở nhà đến đấu trường quốc tế. Điều này thể hiện rằng những người này có một trách nhiệm quan trọng trong cuộc sống, đòi hỏi một sự tận tâm sâu sắc. Tất cả những người Số 6 đều có khả năng tự nhiên này, nhưng thông thường họ hay bị làm khổ bởi lo lắng và bồn chồn đi kèm với trách nhiệm, dẫn tới dễ bị stress. Họ cần học cách làm chủ những tình huống này, qua đó óc sáng tạo của họ được phát triển, chứ không nên để cho bản thân bị cuốn theo những tình huống cùng trách nhiệm ấy. Cuối cùng, họ cần học các buông bỏ bớt, để họ có thể thể hiện được tính sáng tạo tuyệt vời của họ, mà không bị cuốn chìm nổi trong đó."],
    [7, "Có vẻ như rằng những ai sinh ra dưới Con số chủ đạo là số 7 chắc chắn sẽ được ‘rèn giũa’ để qua vòng đời này sẽ tiến lên thêm được một bước dài về phía trước. Đặc điểm nổi bật của Số 7 là khả năng vô hạn được học hỏi thông qua những điều đích thân họ trải nghiệm, qua đó lĩnh hội đựợc những giá trị tốt đẹp và sau đó có thể đem ra chỉ dạy hoặc chia sẻ kinh nghiệm lại cho nhiều người khác. Những trải nghiệm thực tế này còn mang đến cho họ những triết lý sống sâu sắc, ghi khắc dài lâu."],
    [8, "Một trong những khía cạnh rất quan trọng của tình yêu thương là khả năng chúng ta bày tỏ được tình yêu thương ấy. Và một trong những thành tố tối quan trọng để cấu thành một mối quan hệ tốt đẹp giữa người và người chính là khả năng biểu đạt lòng biết ơn và trân trọng đến nhau. Nhưng đây chính là hai phương diện mà những người Số 8 cảm thấy… khó thể hiện nhất. Hệ quả là, mục đích sống quan trọng mà họ cần đạt được trong đời chính là làm sao vượt qua được những điểm giới hạn này. Phát triển theo hướng này sẽ giúp phát triển sự nhận thức mà không làm cản trở sự tự chủ độc lập của họ. Những mối quan hệ được cải thiện như vậy sẽ làm gia tăng niềm tin của những người khác đối với họ. Đổi lại, điều này lại tiếp tục tạo nên cảm giác an toàn cho cá nhân họ và hạnh phúc được cải thiện, cùng với sự phát triển về trí tuệ, một phần cực kỳ cần thiết đối với những người Số 8"],
    [9, "Những người Số 9 luôn tự cảm thấy mình đầy trách nhiệm. Họ phù hợp với nghệ thuật và các lĩnh vực về nhân văn hơn nhiều so với khoa học hay thương mại. Rất nhiều các người đi đầu trong lĩnh vực văn hóa hay ngành diễn xuất (phía chính kịch) có số chủ đạo là Số 9, tất cả những người này đều có lý tưởng cống hiến cháy bỏng cho sự nghiệp và cho cuộc sống, mặc dù các ý tưởng của họ không phải lúc nào cũng ứng dụng được. Vì thế, một điều quan trọng mà họ cần đạt được để hoàn thành mục đích sống của mình, chính là phải học được cách chuyển tải những điều lý tưởng trong đầu họ thành thực tế."],
    [10, "Cuộc sống của những người Số 10 đậm nét hai đặc điểm: khả năng thích nghi và khả năng thay đổi. Độ linh hoạt trời cho có thể hỗ trợ họ tối đa trong việc giúp đỡ người khác điều chỉnh rất nhiều đổi thay trong cuộc sống. Khi đời trở nên phức tạp hơn, việc thích nghi với đời sống bắt buộc cần thiết hơn, chúng ta sẽ thấy người Số 10 có mặt trong rất nhiều phương diện nghề nghiệp hay tình huống. Họ có một lòng can đảm trời cho đưa họ vào những cuộc dấn thân đầy tính tiên phong và những người khác hầu như không bao giờ nghĩ dám thực hiện."],
    [11, "Những người Số 11 nằm trong số ít ỏi những người được trang bị ‘vốn tâm linh’ tiềm tàng tốt đẹp nhất để đưa thời đại chúng ta tiến vào thời đại nhận thức. Nói về mặt tâm linh, đây là một kiếp sống đầy trách nhiệm mà họ đã chọn lựa để có mặt ở cõi đời này. Tuy vậy, thật không may là rất nhiều người trong số họ lại bị quyến rũ bởi những hấp lực mang nặng tính đời trần (hỉ nộ ái ố, yêu yêu hận hận…) để rồi xa lìa mục đích cao cả của mình. Nhưng dòng thủy triều đang thay đổi và hy vọng ngày càng sẽ có thêm nhiều Số 11 nhận ra giá trị thật của mình để quay trở về với những lý tưởng mà họ đã nhận lãnh."],
    [22, "Khi cuộc sống con người không ngừng phát triển tiến hóa về những tầng nhận thức cao hơn, luôn cần có những cá nhân xuất chúng được giao nhiệm vụ dẫn dắt những bước tiến hóa này. Vai trò này quan trọng cũng tương tự như vai trò của một người đạo diễn cho một bộ phim hay một vở kịch vậy. Từ sau hậu trường họ định hướng tất cả, từ thiết kế tổng thế đến mọi ý tưởng, cách thể hiện… Khi sống được tích cực, ở bất cứ lĩnh vực nào trong cuộc sống, những người 22/4 luôn là trung tâm. Trong thời đại nhận thức mới (ý chỉ thế kỷ 21), vai trò của những con người này lại càng trọng yếu hơn nữa, bởi những gì họ nhận thức được có tác dụng như những loại đèn hiệu phát sáng con đường tiến hóa mà theo đó, nhiều người sẽ soi và noi theo. Trong nhiều thế kỷ, những người 22/4 đã chọn lựa âm thầm làm việc đàng sau hậu trường, khi cuộc sống tiến hóa, càng ngày càng có nhiều người 22/4 tiến lên phía trước và đảm trách các vai trò quan trọng hơn bởi cuộc sống ngày càng nhiều điều thật giả lẫn lộn."],
])
const optimalDevelopmentConditions_map = new Map<number, string>([
    [1, ""],
    [2, "Mặc dù rất có khả năng và có niềm tin khi được cho phép làm việc độc lập, theo đúng khả năng làm việc ổn định của mình, người Số 2 có thể cảm thấy không yên tâm nếu bị đặt dưới áp lực làm việc cường độ cao và thường trực. Họ cần được làm việc dưới tốc độ tự nhiên của họ, bởi họ chuộng sự phối hợp nhịp nhàng trong lúc làm việc. Họ đặc biệt đáng quý và không thích lòng thành của họ bị nghi ngờ - điều này cũng sẽ làm giảm sút lòng tự tin của họ. \nBiểu đạt tốt nhất ở người Số 2 nhìn chung thông qua khả năng sử dụng đôi tay nhạy bén của họ, như trong hội họa hoặc viết lách, nhưng luôn luôn phải đặt dưới sự dẫn dắt của trực giác đầy trung thực họ có."],
    [3, "Người Số 3 khi đã gắn bản thân vào công việc rồi thì người khác chạy theo khó kịp bởi tốc độ nhanh chóng của họ. Bên cạnh đó, sự tỉnh táo quá sắc sảo của họ được thể hiện trong hầu hết mọi việc, một số người còn lồng nó vào một kiểu thể hiện khá hài hước đáng ngạc nhiên, làm cho những người này trở thành những người bạn đồng hành sáng chói và thông minh. Họ diễn đạt bản thân thông qua kênh tư duy sẽ thuận lợi hơn nhiều so với diễn đạt cảm xúc hoặc những hành động cụ thể."],
    [4, "Người Số 4 có một trường thể hiện vô cùng rộng lớn, bao trùm hầu hết các công việc cần động tay động chân đến công việc đòi hỏi óc tổ chức. Điều này có thể trải dài, từ việc kiếm tiền như một niềm vui và mục đích chính của cuộc đời, hoặc những thách thức gầy dựng nên những cú làm ăn khủng cho doanh nghiệp, cho đến những khía cạnh thực tế của nghệ thuật và các hoạt động văn hóa, hoặc các hoạt động thể dục thể thao. Cho dù làm bất cứ điều gì, người Số 4 thường thích cách tiếp cận kiểu ‘chính thống’ hơn kiểu trải nghiệm, thích hướng truyền thống chuẩn mực hơn kiểu mạo hiểm phiêu lưu."],
    [5, "Phần lớn những người Số 5 cảm thấy thật khó làm việc theo những giờ giấc quy định nghiêm ngặt. Vì vậy, họ dễ than phiền các sếp của mình và thường chịu… stress về điều này. Họ thường tìm kiếm những công việc cho phép họ không cần phải chịu sự chỉ đạo trực tiếp từ ai, như là công viện nhân viên sales cho các hãng du lịch, các tác giả viết tự do, hay họa sĩ. Bằng cách này, họ sẽ tận hưởng được sự tự do mà họ rất cần để phát triển con đường thể hiện thênh thang của họ một cách phù hợp nhất. Nhiều người rất thèm được đi du ngoạn, và thường hay đi du lịch đó đây hoặc thường xuyên thay đổi công việc. Việc du lịch đây đó hay những trải nghiệm công việc khác nhau này cũng trở thành những phương tiện quý để họ đạt được trí tuệ hay ý thức.\nMột khía cạnh khác mà những người Số 5 rất dễ thành công là lĩnh vực diễn xuất, nơi họ được tự do thể hiện cảm xúc của mình, và nhiều người đã cực kỳ thành công như những diễn viên hay nghệ sĩ chuyên nghiệp. Nhưng có làm gì làm, tình yêu con người ở những người này vẫn là động cơ cơ bản nhất."],
    [6, "Những người Số 6 rất xuất sắc trong các lĩnh vực cần đến lòng tin, óc sáng tạo của họ, cũng như khả năng chăm sóc người khác. Một số người chọn thể hiện tài năng của mình chốn công cộng, tỏa sáng nơi sân khấu hay màn ảnh bằng khả năng diễn xuất hay giọng hát. Một số khác chọn thể hiện bản chất đầy yêu thương của họ một cách riêng tư hơn, ở nhà, với gia đình họ. Cốt lõi của những điều này luôn là một tình yêu sâu sắc dành cho con người, luôn luôn tìm cách được biểu lộ và luôn là một niềm vui để gìn giữ."],
    [7, "Một trong những đặc điểm độc đáo ở những người Số 7 là họ được học hỏi theo cách riêng của họ. Họ chỉ chịu tiếp nhận một mức độ tối thiểu các chỉ dẫn từ người khác, bởi họ khát khao được ‘học’ bằng cách đem bản thân mình ra trải nghiệm. Chính vì điều này, những người Số 7 sẽ thường hay chịu ‘trả giá’ ở ít nhất là một trong ba khía cạnh của cuộc sống: sức khỏe, tình yêu, tiền tài. Để rồi thông qua những bài học này, họ trở thành những người có vốn sống và trải nghiệm sâu sắc để truyền tải lại cho người khác, hay giúp cho đời. Tuy nhiên, những người này sẽ cảm thấy khó sống theo quy củ mà người khác đưa ra, trong khi họ lại thường hay thích áp quy củ của họ lên cho người khác."],
    [8, "Những người Số 8 thường thương cảm những ai đang gặp vấn đề trong cuộc sống. Tuy vậy, thái độ này không phải lúc nào cũng giữ được lâu dài, mà sẽ mất kiên nhẫn với những ai trở nên phụ thuộc vào họ, bởi họ cảm thấy điều này làm phương hại tính độc lập của họ.\nHọ có khả năng trở nên thành công lớn trong công việc kinh doanh, đặc biệt là khi họ không để những nhận định lầm lẫn từ cảm xúc xen vào các quyết định làm ăn của mình.\nNgười Số 8 là những người rất chú trọng chuyện ăn mặc, rất tự hào về vẻ ngoại hình - không chỉ của bản thân mình mà cả những người họ yêu thương hoặc quan tâm. Họ là những người đầy cảm xúc nhưng thường che giấu sự nhạy cảm của mình cho đến khi họ đủ trưởng thành để bày tỏ được ra ngoài."],
    [9, "Những người Số 9 luôn đau đáu ước mong được phục vụ con người, nâng cao đời sống con người. Những người này đầy hoài bão và ước vọng, tuy nhiên họ thường có khuynh hướng đi vào tổng thể chứ ít khi nào tập trung vào chi tiết. Vì vậy, họ phù hợp với những vấn đề không liên quan đến thương mại, buôn bán, bởi họ là những người khá kém cỏi về tính toán hay quản lý tài chính, đặc biệt là trong các vấn đề quản lý tài chính cá nhân (nói nôm na là không biết quản lý tiền đó!) Họ rất có máu nghệ thuật, tuy vậy, nếu có theo diễn xuất, họ thường đi theo hướng diễn xuất nghiêm túc chứ ít chọn phía hài kịch hay các trường phái biểu diễn thoải mái khác."],
    [10, "Nếu chúng ta tìm kiếm một người có thể bầu bạn cùng ta tận hưởng những thú vui nhẹ nhàng trong cuộc sống, không ai phù hợp hơn những người Số 10. Họ tỏ ra vui vẻ nhất khi họ được đắm mình trong những trải nghiệm mà coi là ‘phấn khích bùng nổ’ trong cuộc sống. Nhưng khi họ bị áp lực hoặc bị cản trở về tinh thần, họ xuống tinh thần nhanh chóng mà không rõ nguyên nhân. Điều này làm cho họ trở nên tức giận, thường bộc lộ ra ngoài bằng những hồi nóng nảy hay nổi dịch. Một bộ phận người Số 10 sẽ rất thẳng thắn bộc trực, quyết đoán, tinh thần lạc quan vô biên của họ dẫn dắt họ tới chỗ thành công đáng kể trong cuộc sống. Đây là biểu đạt tự nhiên của Số 10, là một sự kết hợp đầy quyền năng của cái tôi (Số 1), thể hiện chiều sâu tinh thần vô hạn của mình thông qua số 0."],
    [11, "Yêu những gì tinh tế, vẻ đẹp và giá trị văn hóa của đời sống, những người Số 11 dễ thỏa lòng trước những môi trường như vậy bởi nó giải phóng họ được tự do bày tỏ nét đẹp thiên bẩm của tâm hồn. Đời sống vật chất, với nhiều người trong số họ là quá khắc nghiệt và không thú vị. Nhưng họ học cách cân bằng vật chất với những lý tưởng mà họ tìm kiếm và nhận ra rằng những giá trị tinh thần cao quý nhất sẽ chẳng có mấy giá trị, trừ phi chúng có thể mang đến những điều đẹp đẽ làm cải thiện cuộc sống này. Chẳng có biểu đạt nào đẹp đẽ hơn việc dốc mình phụng sự cho cuộc sống, theo khả năng của mỗi người."],
    [22, "Để có được những gì có vẻ là tiềm năng của họ, những người 22/4 trước hết cần nhận được những sự giáo dục tốt nhất có thể. Nhiều người bỏ phần lớn thời gian cho việc học, không ngừng làm cho họ ngày càng giỏi hơn, thỏa mãn khát khao kiến thức. Họ nhận thức được rằng bằng những kiến thức này họ sẽ được trang bị bản thân tốt hơn để hướng dẫn những người khác. Những người 22/4 cần có thể làm việc không có bất cứ trói buộc nào để có thể đạt được hiệu quả cao nhất, bởi họ dễ trở nên tức giận nếu phải làm việc dưới sự điều khiển áp chế quá lâu. Tốc độ học hỏi, lĩnh hội mọi điều của họ nhanh đáng ngạc nhiên, như thể họ đã lĩnh hội được hầu như mọi điều từ các đời kiếp sống trước, và giờ đây chỉ đang lĩnh hội lại lần nữa để làm quen với cách diễn đạt hiện đại của đời sống này mà thôi. Cũng chẳng có gì ngạc nhiên khi họ vươn lên vị trí lãnh đạo rất nhanh chóng, và thường được hỏi ý kiến hướng dẫn hay tư vấn."],
])
const outstandingCharacteristics_map = new Map<number, string>([
    [1, ""],
    [2, "Những người Số 2 đầy nhạy cảm, trực giác tốt, đáng tin cậy, tận tụy và đầy tình cảm. Họ là những nhà hòa giải hoặc người mang đến hòa bình, đôi khi có thể đưa đến khả năng tái cấu trúc lại một tổ chức (và trong thời đại ý thức được đánh giá cao này, đây là một đức tính rất quý). Người Số 2 là người ít bị Cái Tôi chi phối nhất, thể hiện sự nhạy bén và ít vị kỷ đáng quy trong những trường hợp phải hy sinh bản ngã của mình để hòa nhập vào tinh thần chung khi cần."],
    [3, "Đối với những người Số 3, đầu óc cực nhanh nhạy, óc hài hước và sự tỉnh táo rất lý trí nói chung khiến họ dễ dàng đạt được sự thành công trong công việc. Họ có thể trở thành linh hồn của buổi tiệc hoặc là người sáng giá trong công ty, tuy vậy khi ở nhà, họ không phải lúc nào cũng cho thấy rõ như vậy. Họ có thể khá dễ thương, dễ chịu với những người quen sơ sơ, tuy vậy, với những người có gắn bó lâu dài họ dễ tỏ ra hay ‘soi’ lỗi. Điều này có thể gây ra sự mệt mỏi đối với những người sống gần, đặc biệt là bạn đời. Người Số 3 khá thích giúp đỡ người khác, miễn là những người đó có chút tương đồng về ‘đô tư duy’ và những người khác chịu hợp tác với họ."],
    [4, "Người Số 4 có thiên hướng tự nhiên hướng về phía ‘thực tế’ – chẳng thà họ nhào vô làm một việc gì đó chứ không thích ngồi bàn luận về các giá trị việc ấy mang lại. Tình yêu tính thực tế này giúp các người Số 4 lúc nào cũng tiến về phía trước. Họ ít khi nào chịu ngồi yên mà nhìn người khác lu bu việc tổ chức, và thường tiến tới đề nghị phụ một tay. Họ nằm trong số những người nguyên tắc nhất, đáng tin cậy và có thể dự vào. Điều này đặc biệt rõ trong những việc cần sự tỉ mỉ, chi tiết, những nơi mà tính chính xác và khả năng thực tế của họ tỏ ra số một.\nKhi đụng đến các vấn đề thực tế, người Số 4 có thể tỏ ra kiên nhẫn vô bờ bến, nhưng mỗi lần chuyển sang vấn đề gì có liên quan đến khía cạnh tinh thần hay tâm linh, họ thường tỏ ra thiếu kiên nhẫn."],
    [5, "Người Số 5 thường có trực giác rất tốt, với cảm xúc sâu sắc và tư duy nghệ thuật cao, người đạt được niềm vui khôn tả khi được tự do diễn đạt những gì mình đang ấp ủ. Khi được tự do, họ sống động, năng động, nhưng một khi bị gò bó hay ràng buộc, họ trở nên ủ dột và tâm trạng lên xuống bất thường, thậm chí còn có khi lãnh đạm. Tuy vậy, họ là những người tâm tính tốt, quyết tâm sống đời vui vẻ và cũng muốn người khác sống vui vẻ. Đây là một khía cạnh của bản chất từ tâm của họ."],
    [6, "Khả năng sáng tạo xuất chúng của họ thường tìm mọi cơ hội để được thể hiện, ở nơi công sở, lúc vui chơi, hay tại gia đình. Với những người Số 6, nhà họ thường là nơi quan trọng nhất, nó chiếm một khoảng thời gian khá lớn của họ, và đặc biệt là khi có những người thân yêu cùng sống ở đó. Là những người yêu thương con người, những người này rất ghét sự bất công, với mọi hình thức. Họ là những người đầy lòng yêu thương, không ích kỷ, và dễ bao dung, những người phải hết sức để ý để không bị lợi dụng lòng tốt của mình."],
    [7, "Những người này nhìn chung thuộc nhóm những người năng động nhất trong cuộc sống. Mặc dù có thể không ý thức được điều này, nhưng người Số 7 thường có khát khao được tự mình đi qua những trải nghiệm, và những trải nghiệm này sẽ trở nên những kinh nghiệm nhớ đời, bởi (thật không may) phần lớn những trải nghiệm đó sẽ đưa tới những mất mát tổn thất.\nĐường đời của không ít người Số 7 thoạt nhìn có vẻ khá buồn, đặc biệt là khi họ chưa nhận ra những mất mát trở ngại trên đường đời mà họ đang phải trải qua rốt cục là những bài học đời mà họ phải học cho trôi, mà nếu không chịu nhìn ra những kinh nghiệm trước là những bài học, cuộc đời sẽ tái đi tái lại những vấn đề tương tự như vậy, với mức độ tổn thất mất mát ngày càng trầm trọng hơn… cho đến khi nào họ chịu nhìn ra, và chịu ‘học’ kinh nghiệm từ bài này, thì thử thách đó mới dừng lại. Tuy vậy, thông qua việc tổn thất sức khỏe, tình yêu hay tiền tài này, người Số 7 dần dà sẽ ngấm được một loại thấu hiểu triết lý sống một cách sâu xa, và chính sự thấu hiểu quý giá này sẽ giúp họ tránh được những bài học nặng nề hơn khi ý thức của họ ngày càng phát triển.\nNhững người Số 7 có một loại can trường đặc biệt làm cho họ luôn có vẻ rất tự tin mà, chính sự tự tin này giúp họ giải quyết được những bài học cuộc đời một cách kiên cường hơn mắt người ngoài nhìn thấy. Họ hiểu rằng bất cứ điều gì xảy ra phải có một mục đích nào đó, không vô duyên vô cớ xảy ra được."],
    [8, "Điểm nổi bật nhất của người Số 8 là tính độc lập, tự tin và là chỗ dựa đáng tin cậy cho người khác. Chính vì vậy, họ thường là người gánh vác là người chủ chốt trong nhóm hoặc trong công ty. Họ thích hợp nhất với các vị trí quản lý cấp cao về mặt chuyên môn và thường sẽ hoàn thành xuất sắc các nhiệm vụ cấp trên giao.\nMạnh về mặt trí tuệ nhưng người Số 8 thường khó bày tỏ tình cảm của mình. Các nhà Thần số học theo trường phái Pitago còn nhấn mạnh, người Số 8 lại không nhận thấy rằng mình không biết cách biểu lộ tình cảm. Đây là vấn đề thật sự của họ!\nKhả năng chịu áp lực, điều hành là thế mạnh vượt trội của Số 8. Họ có khả năng am hiểu các vấn đề về tài chính và thường hứng thú với các ngành ngân hàng, chứng khoán… Nhờ khả năng che giấu cảm xúc tự nhiên của mình, họ có thể rất thành công trong nghề diễn xuất chuyên nghiệp."],
    [9, "Có hoài bão/tham vọng, có trách nhiệm, có lý tưởng là ba giá trị nổi bật trong con đường tiến hóa của những người Số 9, nhưng trong ba giá trị này, trách nhiệm với bản thân là điểm nhấn đặc biệt. Thật thà là một đức tính tự nhiên của họ, đến mức họ dễ tưởng rằng ai cũng cũng sẽ thật thà như mình. Điều này thường dẫn đến cảm giác thất vọng trầm trọng ở một số người Số 9, thậm chí có một số trường hợp trở nên hoài nghi về tình người, nghi ngờ không biết mình thật thà như vậy có bị… ngu quá không.\nNhững người Số 9 dễ mang tiền tặng cho những người cần đến, hơn là ý thức tiết kiệm để dành lại cho chính mình, và điều này cũng dễ làm cho người thân (đặc biệt là bạn đời) của họ nổi giận. Họ có những ý nghĩ tuyệt đối tốt đẹp về cuộc sống, về lý tưởng sống, về con người và làm sao để truyền cảm hứng sống cho mọi người, bằng cách này hay bằng cách khác.\nMặc dù những ý tưởng đưa ra không phải lúc nào cũng thực tế, nhưng những người Số 9 sẽ luôn nỗ lực để thực hiện chúng, như một phần bản chất của đầu óc đầy hoài bão và lý tưởng sống của họ."],
    [10, "Là một số mang tính thực tế, Số 10 tỏa ra một sức mạnh linh động và khả năng thích ứng để tạo được một cá tính rất được yêu thích. Bản tính vui vẻ của họ nhìn chung mang tính lan tỏa, nhưng bởi vì họ không muốn can dự quá sâu vào các vấn đề của người khác, họ sẽ thấy khó hiểu vì sao người ta lại không vui vẻ hay giỏi thích nghi giống họ. Phần lớn người Số 10 ít đào sâu vào cuộc sống, hài lòng với những thú vui bề nổi, đặc biệt là thể thao – hoặc chủ động tham gia hoặc chỉ làm người xem. Ngược lại, một số ít người Số 10 lại rất ý thức về những giá trị tiềm ẩn ở họ, và trở nên đặc biệt thành công trong nghề nghiệp do có khả năng kiên cường vượt qua những khó khăn trở ngại. Nhìn chung, Số 10 vô thức có một vẻ hòa nhã, tự tin vào bản thân, thể hiện qua cá tính và vẻ ngoài trang nhã, cho dù họ ăn mặc thế nào. Họ không mấy thành công trong việc giải quyết các vấn đề về tâm lý của bản thân hay của những người khác, cũng không phải những nhà tư vấn tài ba trong các mối quan hệ bạn bè, thường thích bầu bạn với các thành viên là người cùng phái hơn người khác phái. Họ cũng nhìn chung rất có máu nghệ thuật, với sự nhạy cảm khiến họ có thể trở thành những nghệ sĩ biểu diễn nhạc cụ tài hoa hay các chuyên gia đánh giá có gu trong quần áo hay các vật dụng khác."],
    [11, "Có những sự khác biệt cực kỳ to lớn giữa cách sống của những người Số 11 nào biết sống tích cực và vận dụng được sức mạnh tâm linh vượt trội của họ vào giúp ích cuộc sống, và những người Số 11 đầy tiêu cực với đời sống có vẻ đầy khó khăn và nhạt nhòa. Khi theo đuổi các vấn đề về tinh thần/tâm linh, những người Số 11 thường có một mức độ cảm nhận giá trị đạo đức cao, một khả năng trực giác cực kỳ nhạy bén, một động lực thôi thúc rất rõ ràng. Khi sống trong môi trường bình thường họ thường tỏ ra những người nhạy cảm, cực kỳ chân thật, có thể tin cậy, công tâm, với một tình cảm sâu đậm dành cho gia đình và bạn bè và một tình yêu cuộc sống chân thành."],
    [22, "Một trong những đặc điểm đáng lưu ý nhất ở những người 22/4 là sự thiếu vắng biểu cảm về cảm xúc. Họ coi việc kiểm soát cảm xúc như một mục đích then chốt, và sử dụng nó để giảm thiểu các phản ứng tiêu cực hướng về họ, thay vì tỏ ra xa rời hay khó hiểu. Thật ra, họ là những người rất nhạy cảm, trực giác cao, là những người hội được sự kết hợp giữa 2 lần ý thức tâm linh mạnh mẽ của Số 11 mà hôm qua mọi người vừa được đọc, cùng với tính thực tế rất hiển hiện của Số 4. Họ hiếm khi từ chối một thử thách nào của cuộc sống, đặc biệt là khi nó liên quan đến an sinh của con người. Họ sẽ được tìm thấy ở một số những môi trường khó khăn và có vẻ nguy hiểm nhất, nhưng thường tỏ ra rất tỉnh táo và thận trọng khi tiến hành bất cứ việc gì mà họ đang hướng dẫn mọi người theo. Khả năng chịu trách nhiệm của họ hầu như vô giới hạn, vì thế có không ít người vô thức có thói quen dựa vào họ."],
])
const developmentRecommendations_map = new Map<number, string>([
    [1, ""],
    [2, "Người Số 2 nên vận dụng trực giác mạnh mẽ của họ để phát triển tính tự tin và chọn lựa được những người bạn hay đối tác làm việc nào có thể đánh giá cao những đặc thù của họ. Điều này rất quan trọng ảnh hưởng đến con đường phát triển cá nhân của họ. Khi họ trưởng thành, người Số 2 sẽ tự động phát hiện ra khả năng kiểm soát cảm xúc, học cách sử dụng nó như một công cụ hỗ trợ để diễn đạt những biểu cảm tinh tế của mình. Nó cũng sẽ rất có lợi cho họ để phát triển các lĩnh vực liên quan đến trí não, đặc biệt là khả năng suy luận và trí nhớ. Sự phát triển theo hướng này sẽ vững chắc khẳng định lòng tự trọng của họ và góp phần đưa đến hạnh phúc cá nhân tốt đẹp hơn nữa."],
    [3, "Người Số 3 nên học phát triển một sự tinh tế cảm thụ cảm xúc của những người khác. Khi họ nhận ra rằng những trải nghiệm đời sẽ luôn luôn mang đến những bài học quý, khả năng cảm thụ của họ sẽ dần dần được cải thiện. Và điều này được cải thiện tốt đến nỗi dần dần họ sẽ học được cách sống chung hòa hợp với người khác. Cuộc sống vì thế sẽ tích cực hơn nhiều.\nHọ không được học việc… cằn nhằn người khác, thay vào đó sử dụng sức bật tự nhiên để lảy ra được nguồn năng lượng dạt dào mới mẻ, nhìn nhận những trải nghiệm kém vui như những cơ hội hữu ích để phát triển. Cũng rất hữu ích cho họ khi học mở rộng kênh diễn đạt từ những gì tiếp nhận được từ trực giác, hay trở nên thực tế hơn trong các giao thiệp hàng ngày, đặc biệt là tại gia đình."],
    [4, "Những người Số 4 cần phát triển ba yếu tố quan trọng sau: thư giãn, áp dụng các bài học về tâm trí, và phát triển trực giác.\nThư giãn là một cách quan trọng để buông bỏ bớt những gánh lo về vật chất, và cả những mối dây liên quan chuyện đời sống thực tế (chuyện cơm áo gạo tiền…) trở nên quá mệt mỏi. Việc thư giãn cũng là một cái nền quan trọng giúp phát triển tâm thức, vốn đạt được hiệu quả nhất thông qua thiền. Bên cạnh đó, việc áp dụng các bài học phát triển tâm trí nằm trong các bài giảng về huấn luyện trí nhớ và thấu hiểu các nguyên tắc quan trọng, thường được dạy trong các chuyên ngành về triết học, kỹ sư, kiến trúc, vv… Những việc ứng dụng như vậy cũng sẽ giúp tăng trưởng trực giác, cánh cổng mở rộng dẫn đến ý thức về tinh thần hay tâm linh.\nCòn trong mọi chuyện mình làm, Số 4 nên cố gắng cân bằng phần thực tế của họ với phần tâm trí (óc phân tích, tính sáng tạo, tính lý tưởng hóa) và phần tinh thần (trực giác, tình yêu thương và độ trí tuệ)."],
    [5, "Thường thì khi người ta tìm kiếm tự do, đó là khi người ta thèm muốn được quay về những ngày tháng vô lo hồn nhiên thuở ban sơ. Nhưng chắc chắn là chúng ta không thể sống mãi với quá khứ, mà phải áp dụng những điều ta học hỏi được thông qua những trải nghiệm trong cuộc sống để phát triển bản thân. Vì thế, mỗi khi có tình huống nào phát sinh trông có vẻ sẽ trói buộc sự tự do của ta lại, thay vì chuẩn bị cảm thấy bức bối, hãy tập trung suy nghĩ về những bài học nào ta sẽ thu nhận được qua trải nghiệm này. Và vì thế, chúng ta sẽ có thể vượt qua được cảm giác khó chịu vì sự bó buộc đó, và tiến lên phía trước được một bước. Sự chấp nhận này sẽ giúp những người Số 5 tăng cường sự chú ý vào các chi tiết, trở nên thực tế hơn, cách nhìn cuộc đời cũng rộng mở hơn. Họ cũng sẽ nhìn ra việc bắt lấy những cơ hội được đi đó đi đây sẽ phát triển khả năng quan sát, và là phương tiện thiết yếu để họ tăng độ hiểu biết về cuộc sống và tăng trí tuệ.\nKhi người Số 5 trưởng thành hơn, họ sẽ nên tự biết điều chỉnh để hài hoà hơn với các kỷ luật, kỷ cương nơi các tập thể họ sống hay sinh hoạt, qua đó tăng lên cảm giác an toàn cho bản thân mình, đặc biệt là trong các mối quan hệ. Trên hết, hãy nhớ rằng người Số 5 là người lấy tình yêu thương làm động cơ cho mọi hành động, cho dẫu họ không phải lúc nào tỏ bày điều đó cho mọi người xung quanh biết."],
    [6, "Những người Số 6 cần luôn nhận thức được rằng một cái nhìn tích cực về mọi điều trong cuộc sống là yếu tố quan trọng hàng đầu để họ phát triển tính sáng tạo, cho dù những điều kiện thực tế có giới hạn đến thế nào. Họ cũng cần hiểu rằng nỗi quan tâm đầy tính tích cực luôn đồng hành với sự tự do thể hiện, không nên đè nén. Vì vậy, họ nên tránh tâm lý sở hữu, sẽ chỉ làm họ khổ mà thôi, thay vào đó, diễn đạt sự quan tâm yêu thương đó đến mọi người xung quanh, đặc biệt là những người thân, bằng nhiều cách khác sáng tạo hơn.\nNhững người Số 6 rất thèm sự bình yên, và mong muốn có được nó bằng mọi giá, nhưng sự cam chịu với hoàn cảnh đôi khi được diễn dịch thành sự yếu đuối, để cuối cùng tự hủy hoại niềm vui của chính họ, dẫn đến mất hạnh phúc, bình an. Phát triển một sự cương quyết đầy khôn ngoan, lúc nào nên thỏa hiệp, lúc nào nên không sẽ cải thiện được hạnh phúc, nó sẽ bảo vệ người Số 6 khỏi bị lợi dụng bởi những người vô tâm (trong đó đôi khi có cả người thân trong gia đình). Nên phát triển khả năng phân biệt cái gì quan trọng, cái gì không, cố gắng lĩnh hội được khả năng dung hòa và thể hiện tình thương yêu của mình một cách khôn ngoan…, tất cả đều giúp họ nâng cao năng lực sáng tạo, giúp họ có thể làm được nhiều điều không thể ngờ tới."],
    [7, "Những người Số 7 không có tính nhận định chính xác hay khả năng am hiểu kinh doanh, nên họ cần cực kỳ thận trọng trong các vấn đề làm ăn kinh doanh hay đầu tư. Nhưng chỉ cần họ hiểu ra hạn chế của họ và chịu ép mình vào kỷ luật hơn bản tính dễ nổi loạn, ít nghe lời, họ có thể tránh được những làm ăn thất bại. Việc chịu khó nghe lời khuyên và sống có kỷ luật cũng sẽ giúp họ phát triển trực giác, dần dà sẽ làm cho hạnh phúc của họ được cải thiện, mà không chỉ cho chính họ, còn cải thiện tích cực đến những người thân người thương của họ nữa.\nThông thường, người Số 7 học khá chậm, do bằng vô thức họ cần tự mình trải nghiệm mọi điều. Với những gia đình có con mang Số 7, các bố mẹ cần lưu ý đặc biệt đến đặc điểm này và nên cho phép con cứ học từ từ theo tốc độ tiếp thu tự nhiên của nó. Vì thông thường có không ít bố mẹ coi chuyện học hành của con ở trường như một dạng ‘thể hiện mặt mũi gia đình’, chứ không nhận ra giá trị lớn nhất của chuyện con đi học là để đạt được những lợi lạc cho bản thân con. Nghiên cứu trên nhiều trẻ em Số 7 cho thấy việc học và tiếp thu kiến thức của các em vẫn nhanh chóng cho đến khoảng năm lên bảy tuổi, để rồi có thể chu kỳ bảy năm sau đó, tốc độ học tập của các em chậm hơn đáng kể, nhưng vào khoảng muòi bốn tuổi trở đi, tốc độ tiếp thu của các em lại được tăng lên cùng với ý thức tự khép mình vào kỷ luật. Trẻ em Số 7 sau này lớn lên ít nào xuất hiện như những học giả sáng chói."],
    [8, "Những người Số 8 cần nỗ lực hết mức để khắc phục vẻ lạnh nhạt, không bày tỏ tình cảm với những người thương xung quanh họ. Quan trọng nhất chính là… làm sao để chính họ tự nhận ra điều này, bởi đa phần người Số 8 không hề nhận ra họ… không biết biểu lộ tình cảm! Khi họ học được cách bày tỏ, hạnh phúc và cả cảm giác an toàn đối với bản thân cũng từ đó mà được cải thiện thêm nhiều. Bày tỏ lòng biết ơn cũng là một phương tiện để họ tập dần khả năng bộc lộ các tầng cảm xúc sâu hơn. Cùng với sự phát triển này, trí tuệ nhìn chung cũng phát triển, điều mà đến trước thời điểm đó, họ chỉ có khuynh hướng biểu đạt nó trong những trường hợp rất ‘công việc’, hoặc khi cần cho người khác lời khuyên mà thôi.\nTrí tuệ và độ trưởng thành của họ sẽ được nâng lên thông qua việc du lịch đó đây, cũng là điều mà họ rất thích thực hiện."],
    [9, "Tính lý tưởng hóa trong tính cách của những người Số 9 làm cho những người này không có con mắt nhìn đúng người, ai họ cũng thấy tốt, ai họ cũng nghĩ là người tốt. Nhưng yên tâm là khi nào họ nhìn ra ‘yếu điểm’ này ở bản thân mình, người Số 9 sẽ có thêm các công cụ thể giúp họ ‘nhìn’ người chính xác hơn. Điều này sẽ giúp họ có các hướng tìm hiểu kỹ càng hơn về một con người cụ thể trước khi đi đến quyết định chỉ dựa trên phân tích chủ quan của họ. Đổi lại, việc nghiên cứu các công cụ 'nhìn người' này sẽ giúp người Số 9 phát triển trực giác và trí tuệ.\nHai yếu tốt quan trọng mà người số 9 cần phải tập trung phát triển là tính kiên nhẫn và lòng kiên định. Bên cạnh đó, như cách họ đang thể hiện trước mọi người, những người Số 9 thường hay bị ‘nghiêm túc quá mức’. Họ cần nhiều không gian và cơ hội để cười to, thưởng thức những trò dí dỏm, vui nhộn mang lại sự cân bằng cho cuộc sống của họ."],
    [10, "Những người Số 10, nếu không tự nhận ra những giá trị của mình sẽ dễ bị chìm khuất trong những quy chuẩn tầm thường. Họ cần nhìn ra tiềm năng của mình để trở nên vượt trội, đó là khả năng linh hoạt và thích nghi cực kỳ mạnh mẽ. Trong suốt vòng đời mình, người Số 10 rất cần các dạng thiền tĩnh tâm để tập trung vào nội tâm và giữ họ kết nối với sức mạnh bên trong. Họ cũng cần vận dụng tính hài hòa trong cuộc sống để phát triển nhận thức về thế giới xung quanh (sự uyên bác), sự hòa hợp trong thái độ, tình cảm và sự kính ngưỡng cuộc sống. Bên cạnh đó, cũng cần học cách phân biệt cái gì quan trọng cái gì không quan trọng , nếu không họ sẽ dễ bị phí thời gian theo đuổi những điều không đáng."],
    [11, "Đối với người Số 11, các lĩnh vực tinh thần không thể bị trộn lẫn với các giá trị thương mại. họ cần chọn lựa những nghề nghiệp có thể tạo điều kiện cho họ phát triển tâm thức và tạo chất liệu cho những sự nhạy cảm đáng quý của họ phát triển. Cùng lúc đó, với sự hào hiệp và nhạy cảm tự nhiên với những yêu cầu từ người khác, người Số 11 thường cần tiền hơn những người bình thường khác (^^) Họ cần phải học không chỉ những cách thức thực tế hơn đê diễn đạt những giá trị tinh thần hay tâm linh của mình, mà còn phải học cách lắng nghe trực giác (vốn rất trung thực, sáng suốt) hơn là bị thúc đẩy bởi những thèm muốn đơn thuần (ví dụ như thèm muốn được ghi nhận, được tưởng thưởng, được trả ơn…) Bên cạnh đó, cũng cần thực tập thêm các đức tính phân biệt rõ ràng nên – không nên làm, hài hòa sống, và can trường sống. Khi gặp hoạn nạn, họ hay từ chối sự giúp đỡ, nhưng phải học cách chấp nhận nhiều hơn và phải học cách nhìn ra những ích lợi có thể thu được từ sự giúp đỡ lẫn nhau đầy thực tế như vậy."],
    [22, "Với những người 22/4, họ rất cần phải đảm bảo được sự cân bằng giữa làm việc và hưởng thụ, vui chơi. Năng lực thiên bẩm trong công việc có thể khiến những người này bị ‘nghiện’ việc, nghiện các thành tựu đạt được trong công việc, qua đó làm tổn hại chất lượng gia đình, mất cả thời gian thư giãn và dành cho các sở thích khác. Cần dành đất cho những sở thích mang tính nghệ thuật như ca hát, nhảy múa, hội họa, viết lách vv… sẽ giúp họ cải thiện biểu cảm và cân bằng cảm xúc. Họ phải nhận ra họ không bao giờ quá già để học hỏi, bởi sự học là một hành trình theo đuổi cả đời với họ."],
])
const suitableCareers_map = new Map<number, string>([
    [1, ""],
    [2, "Những người Số 2 phù hợp nhất làm việc với vai trò trợ lý cá nhân cho các thành viên quản trị doanh nghiệp hay các tổ chức, đặc biệt là các hoạt động giáo dục hay thiện nguyện. Họ cũng rất có máu nghệ thuật, với một độ nhạy cảm cao có thể thể hiện trong hội họa, âm nhạc, ca hát hay nhảy múa, nhưng trong những lĩnh vực này, họ cảm thấy dễ chịu được hòa trong đám đông (tốp ca, nhóm nhảy…) hơn là biểu diễn một mình. HỌ cũng đôi khi được tìm thấy ở những nhà ngoại giao giỏi, nhà hoạt động xã hội, thư ký, và nếu không được nhận nền giáo dục đầy đủ, có thể làm các công nhân trong các dây chuyền nhà máy."],
    [3, "Những người Số 3 hợp nhất với các công việc liên quan đến trí não, bao gồm các lĩnh vực học thuật, đặc biệt là khoa học, kế toán, quản trị kinh doanh, lên phần mềm IT, phân tích hệ thống, vv… Họ cũng có thể là những nhà nghiên cứu khoa học giỏi giang, hoặc diễn xuất trong showbiz, hoặc các nhà lý luận phê bình các bộ môn nghệ thuật."],
    [4, "Những người Số 4 phù hợp nhất làm việc ở những lĩnh vực đòi hỏi kỹ năng cao. Tùy thuộc vào trình độ giáo dục họ nhận được, các công việc có thể rất rộng khắp, từ người làm ăn buôn bán, kỹ thuật viên, nghệ nhân, kỹ thuật viên vận hành máy móc…, hay nhà quản lý trong các doanh nghiệp, vận động viên thể thao chuyên nghiệp, nhà kinh tế, bác sĩ, chuyên viên vật lý trị liệu, người làm vườn… Rất nhiều giảng viên các chuyên ngành mỹ thuật, điêu khắc, các huấn luyện viên thể thao hoặc thể hình, cũng như các tác giả sách hay tạp chí chuyên ngành kỹ thuật nằm trong nhóm người Số 4.\nTrong các lĩnh vực có liên quan tới tài chính, người Số 4 cần ý thức phát triển một đầu óc cân bằng cao độ để đảm bảo họ không bị lôi kéo bởi tính hám lợi cá nhân, một yếu tố do bản chất ‘vật chất’ của Số 4."],
    [5, "Người Số 5 mang ba tính chất đặc trưng trong thể hiện: yêu tự do, thích diễn xuất, và có khiếu nghệ thuật. Vì thế nghề nghiệp nào có yếu tố diễn xuất hoặc cần sự thể hiện chuyên nghiệp sẽ rất hợp với người Số 5. Việc 'diễn xuất hay thể hiện chuyên nghiệp' này không chỉ có ở diễn viên chuyên nghiệp nhen, mà tất cả các ngành nghề cần kỹ năng dạng này, như các nhân viên bán hàng, các chính trị gia... Hoặc họ có thể làm việc trong ngành du lịch hay khách sạn, nhà văn, hoạ sĩ, nhà thiết kế, chủ doanh nghiệp, nhà phát minh sáng chế, nhân viên xã hội..."],
    [6, "Người Số 6 làm gì làm, phải luôn có yếu tố sáng tạo trực tiếp tác động vào cuộc sống của cong người, làm cho cuộc sống con người tốt đẹp hơn. Họ rất giỏi trong các tổ chức nhân đạo, nhân văn, là những người chữa lành, họa sĩ, nhà thiết kế. Họ có một khả năng đáng ghi nhận trong lĩnh vực diễn xuất hay ca hát, tuy vậy một số người sẽ đưa khả năng này đi quá xa, làm cho cuộc sống của họ nhuốm màu ‘drama’ – kịch tính quá mức."],
    [7, "Đáng tin cậy, và ngược lại cũng luôn mong mỏi sự tin tưởng từ người khác, những người Số 7 rất thích hợp trong các hoạt động có liên quan đến ngành luật. Người Số 7 cũng rất hay được tìm thấy trong những người làm công việc giảng dạy, như giáo viên, và các lĩnh vực nhân văn, như thành viên các đoàn thể trong các tôn giáo, nhà khoa học, nhà triết học… Bên cạnh đó, họ cũng là những người có khả năng sử dụng các dụng cụ sắc bén, mà biết bao nhiêu nghề nghiệp cần sử dụng dụng cụ sắc bén, từ ngành Y có bác sĩ phẫu thuật, lao động tay chân có nghề thợ mộc, thợ tiện… Cứ theo khả năng của mỗi người tới đâu, áp vào khung đó là sẽ rất phù hợp."],
    [8, "Những người Số 8 thường được tìm thấy ở các vị trí lãnh đạo các doanh nghiệp lớn, với khả năng điều hành xuất sắc. Họ có khả năng am hiểu cao với các vấn đề về tài chính, và thường hay bị cuốn hút về cách ngành ngân hàng, chứng khoán… Họ cũng sẽ hay được hấp dẫn về các ngành điều phối du lịch, thuyền trưởng hay phi công, giáo viên và y tá phục vụ người già hay trẻ em, làm việc với các loài động vật, hoặc chuyên viên nhân sự cấp cao. Và bên cạnh đó, do khả năng ẩn rất kín cảm xúc tự nhiên của mình sau lớp mặt nạ không cảm xúc, họ có khả năng rất thành công trong nghề diễn xuất chuyên nghiệp."],
    [9, "Những người Số 9 phù hợp, vui vẻ nhất khi được làm việc trong các môi trường tôn giáo, tổ chức an sinh xã hội, viện giáo dục, cơ quan nghiên cứu (bao gồm nghiên ứu IT), giải quyết các vấn đề tội phạm, trị liệu chữa lành…"],
    [10, "Người Số 10 sẽ hợp với các dạng ngành nghề thể thao hay biểu diễn chuyên nghiệp, thiết kế và trang trí nội thất, làm việc với vải sợi và thực phẩm. Họ cũng làm nhân viên sales giỏi, chính trị gia, nhà gây quỹ từ thiện, điều hành doanh nghiệp, giám đốc kinh doanh, hoạch định đô thị, kiến trúc sư, chuyên gia địa ốc…"],
    [11, "Những nghề nghiệp mà Số 11 thường thấy bao gồm nhà giáo dục, nhà hoạt động xã hội, các thủ lĩnh tôn giáo và huấn luyện viên phát triển cá nhân. Hoặc họ cũng có thể là giáo viên các bộ môn văn hóa, biểu diễn chuyên nghiệp. Khả năng trực giác cũng có thể đưa họ đến vai trò các nhà thiết kế hay phát minh tài ba."],
    [22, "Những người 22/4 phù hợp với vị trí lãnh đạo các doanh nghiệp hay tổ chức văn hóa. Họ xuất sắc trên tất cả lĩnh vực họ nỗ lực vươn đến, cho dù đó là nghệ thuật, viết lách, chính trị, các dịch vụ xã giao… hoặc trở thành các chuyên gia đầy hiệu quả, các nhà hoạt động nhân văn, kỹ thuật viên (đặc biệt chuyên ngành IT), và giáo viên."],
])
const negativeTendenciesToOvercome_map = new Map<number, string>([
    [1, ""],
    [2, "Một số người Số 2 không thể nhận ra rằng sự phát triển cố hữu trong họ phải được đi ra từ chính bản thân họ. Đôi khi chủ nghĩa vật chất hoặc một cảm giác Cái tôi giả tạm nào đó xuất hiện sẽ khiến họ trở nên bất ý, nổi sùng và phát hỏa. Khi những tình huống như vậy xuất hiện, họ cần nhận ra ngay rằng họ đang đi dắt đi xa khỏi con đường tiến hóa tự nhiên của mình. Một khả năng khác có thể bị thất vọng nằm ở chỗ dựa dẫm quá nhiều vào tính lý trí mà bỏ qua phần trực giác, điều này sẽ đưa họ đến những phán đoán sai lầm."],
    [3, "Khi sống không mấy tích cực, những người Số 3 dễ bị vướng vào cảm giác ‘cầm quyền’, gia trưởng hoặc chỉ đạo người khác. Điều này có thể gây ra khá nhiều hiểu lầm và mất vui. Bởi tính tỉnh táo quá lý trí, nhiều người Số 3 dễ tỏ ra thiếu kiên nhẫn và kém bao dung với những người kém may mắn hơn về mặt trí não, khá chỉ trích họ về những ‘mặt giới hạn’ này. Nếu không ý thức kiểm soát tốt phần này, điều này dễ bị đem ra áp dụng trong mái gia đình, dẫn đến những cuộc hôn nhân tan vỡ. Trong vài tình huống, việc chỉ trích thường xuyên có thể tạo nên một áp lực nặng nề nơi người bạn đời, khiến người bạn đời… bị tổn thọ ^^ (Đây là nguyên văn của bác tác giả dựa trên hơn 40 năm nghiên cứu với hàng trăm ngàn trường hợp đó nha!)"],
    [4, "Những người Số 4 nhiều khi tỏ ra hoàn toàn bị cuốn hút vào công việc mà xao lãng việc mang đến sự cân bằng cho cuộc sống của họ, đặc biệt là cuộc sống gia đình. Nếu họ không có một khả năng cân bằng cảm xúc một cách mạnh mẽ, họ sẽ dễ mất an yên do những tham vọng/ước vọng không thực hiện được rồi sinh ra tức giận, dẫn đến các vấn đề về tâm lý hoặc những chứng bệnh liên quan đến stress. Thêm nữa, nếu họ không nhận ra nhu cầu về một cuộc sống cân bằng, đời sống họ dễ bị kéo lệch về hướng vật chất. Điều này dần dà dẫn tới cảm giác không an toàn về cảm xúc, và cảm giác không hạnh phúc kinh niên, ảnh hưởng tiêu cực đến sự phát triển mục đích sống của họ ở đời này, đó chính là những phụng sự cuộc sống ở mặt đời sống thực tế."],
    [5, "Vì rất yêu thích tự do, đôi khi người Số 5 có thể chấp nhận những việc làm không mấy ‘chính thống’ để không phải làm việc theo giờ giấc gò bó. Vì thế họ đã không nhận ra được, giá trị tận cùng của sự ‘trói buộc’ rõ ràng như vậy là để tập cho ta tính kiên nhẫn, tinh thần hợp tác, và khả năng tự kiềm chế. Nhiều bạn Số 5 trẻ, khi nhận công việc đầu tiên đã không chịu nổi việc phải nghe lời sếp và… bỏ việc.\nKhi không tập trung chú ý vào chi tiết, người Số 5 dễ bị mắc sai lầm nơi công việc, một vấn đề có khả năng bị làm cho trầm trọng hơn bởi họ bị hồi hộp hay không chắc chắn khi phải giải quyết các công việc mang tính hiện đại. Hệ quả của điều này là họ sẽ dễ bị nổi sùng lên, dẫn tiếp tới stress hay trầm cảm nếu không kiểm soát cảm xúc tốt. Lúc này thì cần phải giữ cho mình bình tĩnh lại bằng cách ra ngoài thiên nhiên hít thở nhiều hơn."],
    [6, "Nếu óc sáng tạo của những người Số 6 bị giới hạn trong phạm vi gia đình, bị nhấn mạnh một cách thái quá, có thể tạo ra tính sở hữu quá đà. Điều này có thể dẫn đến những nỗi lo lắng, bồn chồn thường xuyên xuất hiện, làm cho sự phát triển cá nhân của họ bị giới hạn, và cuộc sống của họ sẽ bị ứ trệ. Nếu để điều này lâu dài, những lo lắng thường trực có khả năng phát triển thành những dạng chướng ngại tâm lý nhẹ, đi kèm với nỗi cô độc buồn bã, mâu thuẫn hoàn toàn với mọi thứ mà người Số 6 đang khát khao muốn sáng tạo. Và khi nỗi lo lắng hay tính tiêu cực hình thành rõ nét trong cuộc sống của người Số 6, giọng họ trở nên bén nhọn, và dần vô thức trở thành một người tính khí khó chịu, hay bắt lỗi người khác."],
    [7, "Do kiểu gì cũng phải trải qua những ‘bài học đời’, trong khi khuynh hướng lại không muốn nhận những lời chỉ dạy hay khuyên nhủ từ người khác, những người Số 7 thường có khuynh hướng rất nổi loạn. Khi từ chối nhận lời khuyên, họ dễ rơi vào khả năng chỉ thích dạy người chứ không thích bị/được người dạy. Ai thấy mình nằm trong khuynh hướng này sẽ phải trả giá nhiều trong cuộc sống, vì họ không học được những bài học kinh nghiệm thương đau mà người khác từng trải qua và khuyên họ nên tránh. Tuy vậy, họ thường thích người khác nghe theo lời khuyên của mình, và khá bực mình khi cũng y những lời khuyên như vậy mà người khác khuyên lại mình. Khi nào họ trưởng thành hơn và lĩnh hội được nhiều trí tuệ hơn, cuộc sống cá nhân và cả công ăn việc làm của họ sẽ trở nên vui vẻ, tốt đẹp hơn nhiều."],
    [8, "Người Số 8 có cá tính mạnh nên có hai phương diện mà họ cảm thấy khó khăn diễn đạt nhất đó là biểu đạt lòng biết ơn và sự trân trọng với người khác. Đây là một thành tố quan trọng để xây dựng mối quan hệ tốt đẹp giữa người với người. Cho nên người Số 8 cần phải vượt qua giới hạn này để cải thiện chất lượng các mối quan hệ.\nTính độc lập mạnh mẽ của người Số 8 khiến họ cảm thấy khó chịu khi có ai đó can thiệp vào kế hoạch hoặc việc làm của họ. Bởi vậy, người sếp nào có cấp dưới là người Số 8 cần lưu ý điểm này và hết sức tinh tế, khéo léo khi muốn góp ý hoặc định hướng công việc cho Số 8.\nTrở ngại của người Số 8 là thể hiện tình cảm của mình với người khác. Họ có lòng trắc ẩn nhưng họ không biết cách thể hiện hoặc biểu hiện của họ khiến người khác hiểu không đúng về ý tốt thật sự trong lòng. Đặc biệt với những có người có gia đình có con, Số 8 hoặc là cưng chiều quá mức hoặc là nghiêm khắc thái hóa. Càng trưởng thành, người Số 8 càng có thể cân bằng lại giữa tính độc lập và cách biểu hiện cảm xúc của mình."],
    [9, "Khi những người Số 9 không áp được những lý tưởng sống họ tìm ra vào những người khác, họ trở nên tiêu cực. Họ cần lưu ý đặc biệt để không trở thành nạn nhân của thói đạo đức giả. Khi ước vọng biến thành tham vọng, các tham vọng của họ có thể thống trị và phá hủy những lý tưởng tốt đẹp họ từng nuôi dưỡng, qua đó vô hình chung phát triển cái gọi là tự tôn. Điều này sẽ sớm tạo thành tính cách thô lỗ và thái độ phê phán thiếu tính xây dựng, làm cho những người xung quanh phải khó khăn chịu đựng, và dẫn đến những hệ quả ít tốt đẹp trong các mối quan hệ, nếu những mối quan hệ này có động cơ xuất phát từ vật chất."],
    [10, "Sự tự tin ở những người Số 10 đôi khi có thể dẫn đến sự thái quá, khiến họ muốn áp chế người khác, nhưng họ hay làm điều đó một cách ít khôn ngoan, dẫn đến sự bất hòa căng thẳng. Khuynh hướng này có thể tránh được thông qua ý thức kiểm soát cái tôi, tái nhận diện độ sâu tinh thần trong mỗi người, và tránh lối sống hời hợt. Việc chủ động tham gia các hoạt động đầy tính xây dựng và sáng tạo cũng sẽ tích cực giúp người Số 10 tiếp nhận thêm những quan điểm thấu suốt hơn, đủ để nhận ra rằng nếu ngày nào một cánh cửa đóng sập lại trước mặt ta, ta chỉ cần quay đi và tìm những cánh cửa mở khác. Họ cũng cần tránh tâm trạng lười biếng và tránh né cuộc sống, và họ cũng cần học cách tự khép mình vào kỷ luật để vượt qua cảm giác buồn sầu và không an toàn về cảm xúc."],
    [11, "Khi đời sống vật chất ngày càng phát triển và nhiều ‘hoa thơm cỏ lạ’ bày ra dọc đường, khả năng người ta bị chia trí, bị cám dỗ và từ bỏ trách nhiệm sống thanh thuần vì những giá trị đạo đức cao cũng dễ xảy ra. Cuộc sống lẽ ra đơn giản, hài hòa hơn nhiều người cảm thấy nhiều. Nhưng những sự phức tạp hoặc thậm chí những đau khổ mà con người ta nhận gánh là do họ bị nhầm lẫn và bước vào, từ đó đi xa ra khỏi con đường chính mà họ nên đi. Khi điều này xảy ra, họ thường cảm thấy cay đắng và hằn học, rồi trở nên thờ ơ lạnh nhạt với những người khác và trong nơi làm việc. Khi những điều này xảy ra với những người Số 11, họ trở nên lạc lối và hờ hững, tìm kiếm ít nhiều sự khuây khỏa trong thế giới vật chất mà họ đang bị dẫn dụ vào. Họ phải giữ ý thức và sự tỉnh thức cao độ để giữ được họ không bị lạc ra khỏi con đường chính mà họ cần đi, bởi nó cũng không quá khó miễn là họ chịu lưu tâm đến trực giác cực kỳ bén nhạy của họ."],
    [22, "Hầu hết những người 22/4 có khả năng tự nhận ra rất nhiều sức mạnh của họ và vận dụng chúng thành công. Một ít người lại không nhận ra, sẽ bị lôi kéo vào một môi trường sống thuần vật chất, qua đó lãnh hết những khía cạnh tiêu cực của Số 4, mà còn tệ hơn. Khi bị cuốn theo hướng này, họ sẽ trở nên những con người lạc lối, ám ảnh vì đồng tiền, và trong lúc chạy theo đồng tiền họ sẽ chịu sự can thiệp bởi sức mạnh vật chất này, trở nên không hạnh phúc, cô độc, lạc lõng. Việc chữa trị những điều này về chiều sâu đòi hỏi rất nhiều sự kiên nhẫn, thông cảm cùng từ ái, bởi những người 22/4 có thể trở thành những người tiêu cực nhất, tương ứng với cán cân đầu bên kia khi họ thành công hay tích cực.\nBởi tất cả những người 22/4 đều rất thích nghệ thuật, nhịp điệu, nhảy múa và hầu hết các thể loại âm nhạc, việc nương vào những hình thức thể hiện thông qua các loại hình nghệ thuật hay giải trí này có thể giúp họ cải thiện thái độ tích cực hơn và cân bằng cảm xúc tốt hơn. Điều này sẽ đưa họ ra khỏi thế giới tự bó gọn của chính họ và giúp họ tái đạt đươc cái nhìn tích cực về cuộc sống."],
])
const summary_map = new Map<number, string>([
    [1, ""],
    [2, "Người Số 2 nhạy cảm, đầy trực giác, năng giúp đỡ, đáng tin cậy, nhà hòa giải, đầy tình cảm và có máu nghệ thuật.\n❗️ Điểm lưu ý từ tác giả: Người mang Số 2 cuối cùng được sinh ra trong thế kỷ 20 là vào ngày ‪1/10/1980‬. Người đầu tiên mang Số 2 sinh trong thế kỷ 21 nhằm ngày 29/7/2000, và sau đó, sẽ có thêm nhiều trường hợp nữa. Vì thế, trong thế kỷ 21, bản chất nhạy cảm của Số 2 sẽ không còn bị ‘khan hiếm’ như ở thế kỷ 20, và vì vậy, hy vọng sẽ góp phần mang đến một thế kỷ trực giác phát triển và hòa bình được tái lập tại nhiều nơi trên thế giới."],
    [3, "Người Số 3 có đầu óc luôn tỉnh táo, hoạt động, đánh giá, suy nghĩ, lên kế hoạch. Họ có một óc hài hước khá thông minh, tuy vậy một số người dễ gặp các vấn đề trong cuộc sống hôn nhân nếu không kiểm soát tốt các phần thiếu tích cực trong cá tính."],
    [4, "Người Số 4 rất thực tế và có vẻ chuộng chuẩn mực, rất thích hướng về vật chất. Họ rất quan tâm tới thể thao và rất khéo tay. Họ là những người thuộc nhóm người ‘làm’ của thế giới."],
    [5, "Bản chất của người Số 5 là đầy yêu thương và yêu tự do, có óc nghệ thuật, máu lãng du, hơi 'moody' (nghĩa là hay 'mưa nắng', hihi), dao động từ tâm trạng rất vui vẻ khi được tự do sang ủ dột ra mặt khi cảm thấy bị 'đè ép'. Họ là những người đầy cảm xúc "],
    [6, "Người Số 6 là những người có đầu óc sáng tạo, hay quan tâm, công bằng, không ích kỷ, bao dung và yêu gia đình, nhưng hay có khuynh hướng bị lo lắng bồn chồn."],
    [7, "Người Số 7 cần học hỏi thông qua các trải nghiệm của bản thân, nhưng không thích những kỷ luật bên ngoài áp vào mình. Họ rất quyết đoán, nhân văn, sâu sắc. Cuộc sống của họ thường phát sinh nhiều vấn đề tổn thất hy sinh mà qua đó, họ sẽ học được nhiều bài học đời để họ tinh thấn hơn về tinh thần. Mình (bạn QH) hạy gọi vui, Con số chủ đạo 7 là số ‘tiền hung hậu kiết’ - nghĩa là 'Kết thúc có hậu'."],
    [8, "Những người Số 8 là những người rất độc lập, chỗ dựa đáng tin cậy, tự tin, ít chịu bày tỏ tình cảm, hợp với thương mại, kinh doanh, và rất quan tâm đến những đối tượng bệnh tật, yếu đuối"],
    [9, "Người Số 9 là những người đặc biệt có trách nhiệm, cực kỳ thật thà, có lý tưởng, đầy hoài bão, luôn hướng về yếu tố nhân văn và rất nghiêm túc về cuộc sống. Họ không biết quản lý tiền bạc, cũng khó tiết kiệm được tiền"],
    [10, "Người Số 10 rất tự tin, hòa nhã, sáng sủa và vui vẻ, với cảm giác tinh nhạy đặc biệt và khả năng bán hàng xuất sắc."],
    [11, "Người Số 11 là những người nhạy cảm, đầy cảm xúc và đầy quan tâm người khác. Họ yêu thích những gì tinh tế, vẻ đẹp và mọi điều về chiều sâu của những giá trị văn hóa, và vô cùng thật thà và giàu tình cảm, thường tránh đời sống kinh doanh quá mệt nhọc, cũng không phải là những người quản lý tiền bạc giỏi."],
    [22, "Đây là con số vua, mà những người mang đúng số này có trách nhiệm nhiều nhất với xã hội. Họ là những người tự tin, có trực giác và nhạy cảm rất cao, với một bản năng kiểm soát cảm xúc mạnh mẽ và một mối quan tâm sâu đậm đến an sinh xã hội. Họ cần hết sức cảnh giác để không trở nên nhẫn tâm gạt bỏ con đường tiến đến mục đích lớn của cuộc đời họ."],
])

// Exporting all Vietnamese Life path number maps
export const ViKeyNumbers = {
    destiny_map,
    overview_map,
    purposeOfLife_map,
    optimalDevelopmentConditions_map,
    outstandingCharacteristics_map,
    developmentRecommendations_map,
    suitableCareers_map,
    negativeTendenciesToOvercome_map,
    summary_map,
}

// Vietnamese translations for Number of Birthday
export const birthday_meaning_map = new Map<number, string>([
    [1, "Số Ngày sinh “1” là những người rất trí tuệ, có cá tính kiêu hãnh. Bạn xuất hiện trong mắt người khác với vẻ độc lập, sáng tạo, và có năng lực lãnh đạo. Số “1” hoàn thành xuất sắc công việc và nhận được sự kính trọng từ các đồng nghiệp. Nếu bị xét nét, số “1” sẽ nổi loạn."],
    [2, "Số Ngày sinh “2” là những người thấu rọi từng khía cạnh của mọi vấn đề. Họ hạnh phúc khi theo đuổi mục tiêu và giỏi làm việc theo nhóm. Số “2” không thường khát khao danh vọng nhưng vẫn truyền cảm hứng đến những người khác. Những người có số này có khả năng tâm linh, và đừng ngạc nhiên nếu người ra hỏi xin bạn lời khuyên."],
    [3, "Số Ngày sinh “3” là những người vui vẻ và là bạn trung thành. Ngoài việc xuất hiện với dáng vẻ nghệ sĩ và giàu trí tưởng tượng, người ra cũng sẽ nhìn thấy bạn thực dụng và, nếu là một người cha/mẹ, thì đó là người giỏi thiết lập trật tự, kỷ luật. Số “3” là những người truyền cảm thụ tuyệt vời, nên người ra thường hỏi xin ý kiến của bạn. Nếu số Ngày sinh “3” không thể tìm được cách để hạnh phúc thì họ rất buồn rầu. Nhưng tin vui là , họ sẽ mau chóng lấy lại trạng thái cân bằng thôi!"],
    [4, "Người ra sẽ cho rằng Ngày sinh “4” là người gọn gàng và giỏi phân tích. Đó là những nhà quản trị cuộc sống và là những nhân viên chăm chỉ. Người ta xem số “4” là chuẩn mực của lòng trung thành và kiên định. Nếu số “4” nghĩ mình đúng thì rất hiếm khi họ rời bỏ vị trí. Để có được uy tín, họ thường đưa ra bằng chứng để chứng minh rằng tại sao họ phải làm như vậy. Họ phải cẩn trọng trong ngôn từ, và tránh lỗ mãng. Những người số “4” này thường bị hiểu lầm. Nói năng nhã nhặn hơn là bí quyết giúp họ có được sự thấu hiểu tốt hơn từ người khác."],
    [5, "Số Ngày sinh “5” là người nhanh nhảu và vui vẻ, và mọi người rất khoái bạn! Nếu có một bữa tiệc nào đó sắp tổ chức, việc bạn tham dự sẽ làm khuấy động nó hơn. Người ta thích tiết lộ những bí mật thú vị nhất cho số “5”. Số “5” cũng được biết đến với tính hiếu động, bởi vì họ rất mau chán. Mục tiêu ở đây cho bạn là: hãy tìm cách để giữ cho trí não luôn khởi động (chẳng hạn như thông qua đọc sách, xem triển lãm nghệ thuật, đi bảo tàng, du lịch, đi tiệc tùng…)."],
    [6, "Số Ngày sinh vào các ngày này là người giàu lòng nhân ái bẩm sinh; họ khát khao tình yêu và tình bạn. Khi một người số “6” bước vào phòng, ngay lập tức bạn nhận ra sự hiện diện của họ. Họ có nguồn năng lực mạnh mẽ. Cả thế giới xem họ đại diện cho phẩm chất vững chãi, biết chịu trách nhiệm và có khả năng quản lý người khác. Số “6” có bản năng chăm sóc trẻ em, và thú nuôi thường quấn quýt với họ."],
    [7, "Số Ngày sinh “7” thi thoảng được xem là những người ít nhiều có nỗi cô đơn. Số “7” có trí thức và tìm kiếm những câu hỏi sâu sắc dạng “Tại sao chúng ta lại ở đây?”. Những người khác có thể cảm thấy bạn khó hiểu. Những người sinh vào các ngày này thường ít khi hài lòng với bản thân dù cho họ đã làm tốt công việc. Họ tạo ra sự khác biệt lớn hơn việc họ nhận thức. Âm nhạc và thiên nhiên tác động sâu sắc đến họ. Họ nên có chúng trong cuộc sống hàng ngày."],
    [8, "Số Với những người có số Ngày sinh “8”, thế giới xem bạn là những người khát khao chất lượng sống. Hầu hết người số “8” sẵn sàng làm việc cật lực. Bạn thích những người xinh xắn, có trật tự, và tự hào về ngôi nhà cùng gia đình yêu dấu của mình. Ưu tiên đặt ra với bạn là tìm cách để duy trì sức khỏe tốt và an toàn. Những người mang con số này thường bị quy kết là khó gần. Vì vậy, họ nên cố gắng bày tỏ lòng nhiệt thành của mình.Số Với những người có số Ngày sinh “8”, thế giới xem bạn là những người khát khao chất lượng sống. Hầu hết người số “8” sẵn sàng làm việc cật lực. Bạn thích những người xinh xắn, có trật tự, và tự hào về ngôi nhà cùng gia đình yêu dấu của mình. Ưu tiên đặt ra với bạn là tìm cách để duy trì sức khỏe tốt và an toàn. Những người mang con số này thường bị quy kết là khó gần. Vì vậy, họ nên cố gắng bày tỏ lòng nhiệt thành của mình."],
    [9, "Số Ngày sinh “9” được xem là người thân thiện. Thế giới cần bạn cho lời khuyên – người lạ mong bạn chỉ dẫn! Mọi người luôn tin là số “9” có thể giúp được họ. Số Ngày sinh “9” toát ra vẻ tin cậy đến nỗi người khác tin họ hoàn toàn, thậm chí tiết lộ cho họ những bí mật sâu kín nhất. Số “9” có thể thể hiện vẻ trịnh thượng nên phải xem xét lại lời nói trong cách giao tiếp của họ. Người số “9” phải thiết lập ranh giới tích cực với gia đình nguyên thủy của họ để có thể sống hạnh phúc và hòa bình."],
    [10, "Số Ngày sinh “1” là những người rất trí tuệ, có cá tính kiêu hãnh. Bạn xuất hiện trong mắt người khác với vẻ độc lập, sáng tạo, và có năng lực lãnh đạo. Số “1” hoàn thành xuất sắc công việc và nhận được sự kính trọng từ các đồng nghiệp. Nếu bị xét nét, số “1” sẽ nổi loạn."],
    [11, "Là Số Ngày sinh 11/2, bạn có khả năng đạt được chiều sâu của sự hiểu biết ngoài năm của bạn. Bạn sáng tạo, thông minh và nhiệt tình, nhưng bạn phải vượt qua sự bất an và tin tưởng vào chính mình. Bạn là một cố vấn và người chữa bệnh tự nhiên, với khả năng nâng đỡ và truyền cảm hứng cho người khác, trực giác và sự sáng suốt nâng cao của bạn cho phép bạn đạt đến mức độ am hiểu và nhận thức cao hơn. Cân bằng, tự tin và trung thực là chìa khóa thành công của bạn."],
    [22, "Vào ngày sinh nhật 22/4, bạn được trao tặng khả năng cai quản hoặc xây dựng một cái gì đó vì lợi ích của người khác. Bạn là một người có tầm nhìn chăm chỉ, có khả năng biến giấc mơ thành hiện thực, nhưng bạn phải học cách làm chủ sự mẫn cảm và bất an của số 2 trong quá trình này. Cách tiếp cận hợp lý, thực tế và có phương pháp của bạn khiến bạn trở thành một nhà tổ chức và quản lý tài năng; tuy nhiên, một bài học cuộc sống khác là giữ cân bằng, có căn cứ và kiên định khi đối mặt với nghịch cảnh và khó khăn."],
])

export const lifeAdditude_meaning_map = new Map<number, string>([
    [1, "Bạn tự chủ và có lòng tự trọng cao nên luôn tự mình làm mọi việc mà không muốn nhờ người khác giúp đỡ. Nhưng đôi khi bạn vẫn nghĩ rằng mình không đủ giỏi nên bạn khao khát được người khác ca ngợi. Chỉ cẩn người khác tin tưởng bạn, bạn sẽ không làm họ thất vọng, nếu không bạn sẽ nổi loạn."],
    [2, "Bạn là người dịu dàng. Bạn thích quan sát mọi người và cuộc sống xung quanh. Bạn lãng mạn, nên bạn cần yêu và được yêu. Bạn dễ bị lôi cuốn bởi bất cứ thứ gì liên quan đến năng lực huyền bí hoặc ký ức ảo giác. Tức là bạn cảm thấy quen thuộc trong một môi trường, khung cảnh mới nhưng không nhớ đã từng trải qua khi nào.  Bạn có những giấc mơ sẽ trở thành sự thật. Bạn có thể chạm đến trực giác của mình và khía cạnh siêu hình của cuộc sống. Bạn có lòng trắc ẩn và thích nghe những câu chuyện của người khác mà không cảm thấy chán nản. "],
    [3, "Bạn có khiếu hài hước hay pha trò và uy tín. Bạn trưởng thành nhưng mang tâm trí của đứa trẻ. Nhưng mỗi khi bạn có tâm trạng tốt, bạn sẽ chuyện trò với nụ cười rạng rỡ và ánh mắt long lanh. Nhưng khi không vui, bạn sẽ ảnh hưởng tâm trạng xấu cho người khác và họ không muốn đến gần bạn. "],
    [4, "Đôi khi bạn trầm mặc khiến người khác cảm thấy khó hiểu về bạn. Bạn hiểu rõ những gì đang diễn ra. Bạn thích hòa mình vào thiên nhiên. Bạn phù hợp trở thành kiểm toán viên, lĩnh vực sửa chữa hay xây dựng. Bạn dạy dỗ và hướng dẫn mọi người. Bạn đưa mọi mặt của một vấn đề ra cho mọi người hiểu. Bạn biết ai đang nói dối và bạn sẽ vạch trần họ. "],
    [5, "Bạn luôn mang lại hình ảnh tươi sáng, sống động, dũng cảm và dễ nắm bắt sự thay đổi. Bạn vui vẻ, thường xuyên than vãn và đánh giá cao việc trở thành tâm điểm trong đám đông.\nBạn khá nhạy cảm và rất cảnh giác khi tiếp xúc với người mới. Bạn dũng cảm đặc biệt có trách nhiệm hơn trong việc đi du lịch và trải nghiệm thế giới.\nNhược điểm: Bạn có xu hướng sử dụng chất kích thích nhiều hơn, quan hệ tình dục và uống rượu nhằm thỏa mãn cảm giác tự do của mình."],
    [6, "Bạn giỏi nuôi dưỡng và chăm sóc chu đáo cho bất kỳ ai. Còn nếu bạn có một đứa con mang số “6”, nó sẽ phản ứng như thể nó là cha hay mẹ bạn vậy. Bạn muốn đảm đương mọi việc thay vì người khác sai bảo bạn; Bạn thấy mình hữu ích nhất là khi mọi thứ đang mất kiểm soát và bạn sẵn sàng sửa chữa chúng. Còn khi mọi thứ yên ổn, bạn sẽ thấy mình thừa thãi. Khi số “6” bước vào phòng, người khác sẽ bị bạn lôi cuốn."],
    [7, "Bạn sống nội tâm, chất chứa nỗi niềm nên không ai hiểu bạn đang nghĩ hay cảm nhận điều gì. Bạn luôn tìm kiếm câu trả lời cho câu hỏi “Tại sao mình lại ở đây?”  Số Thái độ “7” không gặp vấn đề gì khi hỏi thẳng nhưng sẽ đề phòng nếu bị người khác hỏi dù chỉ một câu như thế. Bạn tiết lộ bản thân một cách úp mở. Khi bạn im lặng, mọi người nghĩ bạn không hứng thú với những điều họ nói. Nhưng thực tế bạn vẫn quan sát mọi người và không bỏ lỡ câu chuyện nào. "],
    [8, "Số Thái độ “8” sẵn sàng trải lòng ra với người khác. Bạn thể hiện sự hài hước và cái nhìn lạc quan với cuộc sống, nhưng đôi khi người khác lại thấy hơi lỗ mãng. Bạn thường đọc tạp chí dành cho các nhà đầu tư hoặc nghĩ cách làm sao xây dựng tài chính an toàn cho bản thân để có một cuộc sống tốt hơn. Nếu bạn có gia đình thì bạn muốn là người ủng hộ tuyệt vời. Bạn không giỏi giữ tiền, nhưng lại dễ kiếm lại số tiền đã dùng. Số Thái độ “8” phải xem mỗi ngày là một cơ hội bắt đầu mới. Bạn buộc phải rũ bỏ quá khứ, vất bỏ những ý nghĩ tiêu cực, nếu không muốn bị cản trở niềm hạnh phúc có được ở hiện tại."],
    [9, "Số “9” là thủ lĩnh. Trong công việc, bạn thích ôm nhiều việc vào mình.  Bạn làm luôn phần việc của mình và cho người khác, nên nhiều người thường ỷ lại và trông chờ vào bạn. Nếu tuổi thơ của bạn không tốt đẹp, hãy để gió cuốn đi, đừng để muộn phiền đeo bám bạn đến hiện tại. Mặc dù bạn rất nhiệt tình giúp đỡ người khác, nhưng cũng hãy chăm lo đến sức khỏe của mình đề phòng bị kiệt sức."],
    [10, "Bạn tự chủ và có lòng tự trọng cao nên luôn tự mình làm mọi việc mà không muốn nhờ người khác giúp đỡ. Nhưng đôi khi bạn vẫn nghĩ rằng mình không đủ giỏi nên bạn khao khát được người khác ca ngợi. Chỉ cẩn người khác tin tưởng bạn, bạn sẽ không làm họ thất vọng, nếu không bạn sẽ nổi loạn."],
    [11, ""],
    [22, ""],
])

export const birthday_chart_meaning_map = new Map<string, string>([
  ["-1", `Số 1 thể hiện tự chủ, biểu tượng thể hiện cá tôi , cách thể hiện cái tôi hoặc dè nén cái tôi, thiếu tự chủ. Họ bị khó khăn trong diễn tả cái học đang nghĩ. Nhiều bạn được đánh giá là lãnh đạm, lạnh lùng, và dễ bị hiểu lầm trong lời nói... thực ra do họ không biết và không thể thể hiện được suy nghĩ mình. 
Ngoài ra, những bạn thiếu số 1 là những bạn khá thụ động, hay trì hoãn.\n\n(+) Điền số 1 ảo:\n- Học cách suy nghĩ cẩn trọng trước khi phát biểu, tập phản ứng chậm lại trước các ý kiến, lời phê bình…. Bởi vì lời nói đã phát ra khó thu hồi lại được, mà cảm giác thương tổn cũng khó mà hàn gắn.\n- Viết nhật ký, tập cách chia sẻ suy nghĩ với bạn bè người thân mà bạn cảm thấy tin tưởng nhất.\n- Tập thiền hoặc yoga...2 môn này bạn có thể tự tập tại nhà hoặc ra các cơ sở để có người hướng dẫn. Nhưng nếu bạn không có đủ thời gian để ra các phòng Gym, bạn có thể đăng ký học qua các lớp dạy online.`],
  ["-2", `Đừng lầm cho rằng một người không có số 2 trong biểu đồ ngày sinh thì sẽ hoàn toàn thiếu vắng trực giác hay độ nhạy cảm. Đúng hơn, việc không có số 2 chỉ muốn nhắc rằng người này cần phát triển trực giác và độ nhạy cảm nhiều hơn.\n\n(+) Điền số 2 ảo:\n- Tập những hoạt động tăng trực giác\n- Tập thiền và yoga.\n- Đọc kinh chú: bạn theo hoặc tin 1 tôn giáo nhất định đều có những quyển sách như vậy.\n- Ho’oponopono: phương pháp thiền của người hawai cổ đại. Cái này bạn tự tìm hiểu nhé, có rất nhiều sách nói về ho’oponopono ở ngoài nhà sách đấy. Mình đọc qua quyển: Ho’oponopono: Sống Như Người Hawaii – Chấp Nhận, Biết Ơn Và Tha Thứ. Đây chắc là 1 trong những quyển nói về ho’oponopono được nhiều người biết đến nhất ở Việt Nam, bạn có thể mua online theo link bên dưới.`],
  ["-3", `Người thiếu vắng số 3 trong ngày sinh không có nghĩa người ấy yếu về phần trí, ngoại trừ khi người ấy không chống nổi tính lười và/hoặc tánh thờ ơ không quan tâm. Nói chính xác hơn, người thiếu số 3 sẽ cần cố gắng nhiều hơn trong các lĩnh vực phát triển tâm trí, đặc biệt là khi Con số chủ đạo của họ cũng không nằm trong nhóm số trí não nốt (tức không nằm trong các nhóm số 3,6,9). Tuy vậy, khuynh hướng ngả vào tính lười biếng ở những người này cũng cần được ghi nhận và điều chỉnh từ những năm tháng tuổi thơ, nếu không, điều này sẽ gây ra nhiều khó khăn cho họ sau này.\n\n(+) Điền số 3 ảo\n1/ Phá thế bằng TÊN RIÊNG có chữ C, L, U tương ứng với số 3. Bản thân những chữ cái trong cái tên cũng có những sóng rung tương ứng.\n2/ Ý nghĩa của Số 3 nằm ở bộ nhớ, ở việc học. Vì vậy, muốn có con số 3 ‘Ảo’ trong biểu đồ ngày sinh của mình, bạn chỉ cần luôn nhớ tìm HỌC một cái gì đó, là được. Tìm học bất kỳ thứ gì bạn quan tâm. Học làm bánh, nấu ăn, cắm hoa, tỉa củ, làm vườn…; học sơ cấp cứu, bấm huyệt, yoga…, học Phật pháp, học làm thơ làm văn học vẽ học chụp ảnh… Tóm lại, miễn sao bạn giữ bạn gắn liền với việc Học Hỏi, là tiềm thức của bạn sẽ tự đọc gắn Số 3 vô biểu đồ ngày sinh của bạn, từ đó, bạn vừa thoát khỏi trí đa nghi, hay vui buồn bất chợt.`],
  ["-4", `Biểu đồ ngày sinh vắng số 4 (nghĩa là trong ngày sinh không có số 4) diễn tả người này tánh thường thiếu kiên nhẫn, nhưng mức độ thiếu kiên nhẫn sẽ còn thể hiện rõ ở những lĩnh vực nào thì còn phụ thuộc vào một số yếu tố khác, chẳng hạn như Con số chủ đạo, hay ngày sinh, hay các Mũi tên chỉ cá tính.\n\nChẳng hạn, người thiếu số 4 nhưng lại có đủ ba số 3-6-9 (Mũi tên Trí nhớ) sẽ thấy rất thiếu kiên nhẫn với những ai chậm hiểu. Những ai thiếu số 4 mà có đủ ba số 2-5-8 (Mũi tên chỉ Cân bằng cảm xúc) sẽ thấy thiếu kiên nhẫn với những ai không thể kiểm soát được cảm xúc của mình… Những sự thiếu kiên nhẫn như thế này có thể dần dần được cải thiện nếu ta ý thức được về điểm này và chú tâm vào từng chi tiết khiến những người kia bị yếu, và dùng lòng quan tâm, lòng thương của mình để cải hóa tánh khó chịu của mình dần dần, sẽ ổn.\n\n(+) Điền số 4 ảo: con số thể hiện năng động và thực tế.\n- Phụ giúp mọi người trong gia đình làm những việc nhỏ trong nhà: nấu cơm, rửa chén, quét dọn….`],
  ["-5", `Người không có số 5 cũng là một sự thiệt thòi, vì nó hay dẫn đến những chỗ trống thành dãy ba số liền mạch ở các trục ngang chỉ tâm hồn (như 2-5-8) hay trục dọc (như 4-5-6) và cả hai trục xéo (như 1-5-9 hay 3-5-7), dẫn đến những Mũi tên trống chỉ nhiều bất lợi trong cá tính. Con Số 5 vô cùng cần thiết và quan trọng, có vai trò vị trí trung tâm, giống như tâm của đóa hoa, là cái nhân của một mạn đà là – một đàn tràng từ đó tỏa ra năng lượng tích cực, kết nối với tất cả các số còn lại. \n\n(+) Điền số 5 ảo:\n1/ Phá thế bằng TÊN RIÊNG có chữ N, E, W tương ứng với số 5. Bản thân những chữ cái trong cái tên cũng có những sóng rung tương ứng.\n2/ Chịu khó diễn đạt mình tự do, thoải mái hơn, vui buồn gì đều không tự giữ trong lòng.\n3/ Tập mở lòng và kết nối với mọi người xung quanh mình chủ động hơn, không tự cô lập mình.\n4/ Tập bày tỏ yêu thương đến mọi người, muôn loài thường xuyên hơn. Bày tỏ sự biết ơn với muôn người, muôn loài.\n5/ Tập đứng trước đám đông và diễn đạt ý kiến mình, mạnh dạn hơn. Nếu chưa làm được, khuyến khích tham gia các lớp kỹ năng sống, tâm lý sống hay các câu lạc bộ, đội nhóm...\n6/ Tập yoga hay các hoạt động thể dục tương đương. Lưu ý đến vùng cổ họng. Nơi đây có Luân xa số 5 – Trung tâm năng lượng có liên quan đến giao tiếp, kết nối. Khi chúng ta tập trung cho vùng Luân xa số 5 này thông suốt, con Số 5 Ảo sẽ từ từ được ‘điền’ vào Biểu đồ ngày sinh của bạn.`],
  ["-6", `Biểu đồ vắng số 6 chỉ ra rằng bạn cần phát triển óc sáng tạo thông qua các vùng mà các số khác họ có phụ trách. Nếu bạn có số 3, việc này sẽ dễ thực hiện hơn. Nếu không có số 3 luôn, bạn cần phải huy động nỗ lực tận tâm hơn mới mong phát triển tốt cá tính của mình.\n\n(+) Điền số 6 ảo:\n1/ Phá thế bằng TÊN RIÊNG có chữ F, O, X tương ứng với số 6. Bản thân những chữ cái trong cái tên cũng có những sóng rung tương ứng.\n2/ Con số của sự sáng tạo, vậy bạn nên học 1 môn nghệ thuật như âm nhạc, vẽ, viết blog…. tất cả những môn nghệ thuật này đều gắn liền với sự sáng tạo.\n3/ Học cách thể hiện tình thương của mình với mọi người, sự vật, sự việc ở trên nhiều phương diện khác nhau. Khuyến khích gắn bó với gia đình, làm các việc nhà, sắp xếp phòng, nhà cửa, tưới cây, trồng hoa… vừa tăng ý thức với thiên nhiên vừa gắn bó với mái ấm nhà mình.`],
  ["-7", `Những người thiếu con số 7 trong biểu đồ ngày sinh sẽ nằm trong hai trường hợp:\n+ Hoặc là con người này đã vượt qua được những bài học hy sinh trong những kiếp sống trước đây nên kiếp này khỏi cần học lại thêm nữa (thật đáng mừng thay);\n+ Hoặc là (trường hợp này phổ biến hơn), nó ám chỉ rằng con người này chưa hiểu được giá trị của hạnh hy sinh, và họ phải nỗ lực chủ động thực hiện trước để tự cảm nhận giá trị này\n\n(+) Điền số 7 ảo: Bắt tay vào làm những thứ mà bạn cho là đúng để mình tự trải nghiệm qua nó rút ra được bài học cho bản thân mình.`],
  ["-8", `Những biểu đồ ngày sinh hoàn toàn không có con số 8 chỉ ra rằng những người này cần phải nỗ lực nhiều để đạt được độ độc lập hay trí tuệ đáng mơ ước, làm cho cuộc sống của họ thêm đầy đặn và đáng sống hơn nữa.\n\n(+) Điền số 8 ảo:\n- Tập những hoạt động tăng trực giác\n- Tập thiền và yoga.\n- Đọc kinh chú: bạn theo hoặc tin 1 tôn giáo nhất định đều có những quyển sách như vậy.\n- Ho’oponopono: phương pháp thiền của người hawai cổ đại. Cái này bạn tự tìm hiểu nhé, có rất nhiều sách nói về ho’oponopono ở ngoài nhà sách đấy. Mình đọc qua quyển: Ho’oponopono: Sống Như Người Hawaii – Chấp Nhận, Biết Ơn Và Tha Thứ. Đây chắc là 1 trong những quyển nói về ho’oponopono được nhiều người biết đến nhất ở Việt Nam, bạn có thể mua online theo link bên dưới.`],
  ["-9", `Không có số 9 trong ngày sinh không có nghĩa là bạn không có trách nhiệm, hoài bão hay lý tưởng. Điều này chỉ muốn nhắc nhở các cá nhân này cần nỗ lực hơn nữa để thể hiện những giá trị này rõ nét hơn, để tạo nên một xã hội hài hòa, luôn tiến về phía trước với sự cân bằng, điều độ.\n\n(+) Điền số 9 ảo: Tự đặt cho mình những mục tiêu nho nhỏ để thực hiện, ví dụ như tuần này mình sẽ đọc hết 1 quyển sách, tháng này mình sẽ để giành 500k…..sau khi đạt được những mục tiêu nhỏ hãy đặt những mục tiêu to dần lên nhưng vừa với khả năng của bạn ở thời điểm đó.`],

  // 1
  ["1", ``],
  ["11", ``],
  ["111", ``],
  ["1111", ``],
  ["11111", ``],

  // 2
  ["2", ``],
  ["22", ``],
  ["222", ``],
  ["2222", ``],
  ["22222", ``],

  // 3
  ["3", ``],
  ["33", ``],
  ["333", ``],
  ["3333", ``],
  ["33333", ``],

  // 4
  ["4", ``],
  ["44", ``],
  ["444", ``],
  ["4444", ``],
  ["44444", ``],

  // 5
  ["5", ``],
  ["55", ``],
  ["555", ``],
  ["5555", ``],
  ["55555", ``],

  // 6
  ["6", ``],
  ["66", ``],
  ["666", ``],
  ["6666", ``],
  ["66666", ``],

  // 7
  ["7", ``],
  ["77", ``],
  ["777", ``],
  ["7777", ``],
  ["77777", ``],

  // 8
  ["8", ``],
  ["88", ``],
  ["888", ``],
  ["8888", ``],
  ["88888", ``],

  // 9
  ["9", ``],
  ["99", ``],
  ["999", ``],
  ["9999", ``],
  ["99999", ``],
])
